### ISSUE TITLE
🐛 Bug Report: Langchain ChromaDB RAG template does not seem to work 

### ISSUE THREAD

**Issue by slice4e** [traceloop/openllmetry#1008]
### Which component is this bug for?

Langchain Instrumentation

### 📜 Description

The ChromaDB instrumentation worked for me when using the provided sample app. However, when using a Langchain RAG implementation with ChromaDB, here: https://github.com/langchain-ai/langchain/tree/master/templates/rag-chroma  
I did not work for me. 

### 👟 Reproduction steps

Download the Langchain ChromaDB RAG template: https://github.com/langchain-ai/langchain/tree/master/templates/rag-chroma 
Modify chain.py to enable Traceloop. (import and Traceloop.init). 

### 👍 Expected behavior

Expected to see the spans in the web GUI

### 👎 Actual Behavior with Screenshots

Did not see the spans. 

### 🤖 Python Version

3.11

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
This should work, see [this example](https://github.com/traceloop/openllmetry/pull/1043). Because LangServe uses uvicorn you need to initialize Traceloop in the same file as the chain itself, and not in the server.py file - as they "live" in separate python contexts
