### ISSUE TITLE
🚀 Feature: Support Google's alternative package for Gemini

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry#1026]
### Which component is this feature for?

All Packages

### 🔖 Feature description

Add support for `google-generativeai` - another package that Google provides for connecting to Gemini models.
This should be pretty similar to our current support in VertexAI

### 🎤 Why is this feature needed ?

Completion of OpenLLMetry support in LLM providers.

### ✌️ How do you aim to achieve this?

1. Write a new sample app that uses `google-generativeai` to call Gemini
2. Copy-paste the vertex AI instrumentation
3. Change method / classes name according to how they're named in `google-generativeai`
4. Add Tests

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by MarkWinter21** [comment]
I'm happy to take a look at this. Could you send on any supporting info you might think relevant to help me get started? Thanks

**Comment by nirga** [comment]
@MarkWinter21 I think this is a good place to start:
https://ai.google.dev/gemini-api/docs/quickstart

**Comment by MarkWinter21** [comment]
Hi, I just did some research and realised as I'm based in Europe a region where the Gemini API is not available that I'd have to go via Vertex AI. Do you think that will be a problem?

**Comment by nirga** [comment]
@MarkWinter21 huh... yeah actually. How about [this one](https://github.com/traceloop/openllmetry/pull/1025) - we need to figure out what it takes to update weaviate to 4.6.0

**Comment by Josecespedesant** [comment]
Hello! I will give it a try

**Comment by nirga** [comment]
Fixed with #1293
