### ISSUE TITLE
🚀 Feature: Add support for streaming in Langchain instrumentation

### ISSUE THREAD

**Issue by damianoneill** [traceloop/openllmetry#1101]
### Which component is this feature for?

Langchain Instrumentation

### 🔖 Feature description

Today, for Langchain, the solution will automatically instrument invoke and subsequently generate methods.  It would be great if this functionality could be extended to include the stream / _stream methods of Runnable as well, see https://python.langchain.com/v0.2/docs/concepts/#runnable-interface 

### 🎤 Why is this feature needed ?

With the move to more complex language models and subsequent increases in response times, a significant number of LLM providers are aggressively pushing streaming, both sync and async as the primary interface to their solutions.

### ✌️ How do you aim to achieve this?

I'm sorry, but I don't understand the internals of traceloop SDK. From an external perspective, I'd like to see tasks extended so that calls to the stream endpoint would be visible in a workflow.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
Thanks @damianoneill! We'll work on adding this and I'll update here when it's ready
