### ISSUE TITLE
🐛 Bug Report: missing package dependencies

### ISSUE THREAD

**Issue by tibor-reiss** [traceloop/openllmetry#1133]
### Which component is this bug for?

All Packages

### 📜 Description

Some explicit dependencies are only available through installing test (or dev) dependencies. Here is a list I found so far with the opentelemetry-instrumentation package first and the missing dependency second:
- anthropic -> anthropic
- bedrock -> botocore
- chromadb -> chromadb
- llamaindex -> llama-index
- milvus -> pymilvus
- openai -> openai
- pinecone -> pinecone
- qdrant -> qdrant_client
- transformers -> transformers

### 👟 Reproduction steps

Here is an example for milvus (same when installing everything via traceloop-sdk):

1. create a venv
2. pip install opentelemetry-instrumentation-milvus
3. start python
4. from opentelemetry.instrumentation.milvus import MilvusInstrumentor

### 👍 Expected behavior

No error

### 👎 Actual Behavior with Screenshots

Python 3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

`from opentelemetry.instrumentation.milvus import MilvusInstrumentor`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/tibor/VENV/venv_wsl_pymilvus/lib/python3.11/site-packages/opentelemetry/instrumentation/milvus/__init__.py", line 4, in <module>
    import pymilvus
ModuleNotFoundError: No module named 'pymilvus'
```

### 🤖 Python Version

Python 3.11.9

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by nirga** [comment]
Hey @tibor-reiss this is on purpose. The user installs the packages it actually uses and we [detect that automatically in the SDK](https://github.com/traceloop/openllmetry/blob/2c5caf3e7cae67c07d458031e0065c4510e3de30/packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py#L456). If we added all these dependency it will force the user to install `pymilvus` for example even if they don't actually use it.

**Comment by tibor-reiss** [comment]
That's an interesting PoV. I might be wrong, but isn't the convention to have these packages then defined as optionals/extras, i.e. install them with the square brackets?

**Comment by nirga** [comment]
No, because this isn't an extension to the traceloop sdk package, but rather a separate package altogether.

This is also the convention other OpenTelemetry packages are using.

**Comment by tibor-reiss** [comment]
Thanks @nirga for the explanation, interesting to see different approaches in the open source community.
