### ISSUE TITLE
🚀 Feature: extract semantic conventions

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry#117]
### Which component is this feature for?

All Packages

### 🔖 Feature description

As the instrumentations grew, there are some semantic conventions that should be extracted out of the individual packages into the common one, namely:

- LLM prompts
- Prompt keys
- Whether to disable prompt logging for privacy reasons

### 🎤 Why is this feature needed ?

Order in the repo :) 

### ✌️ How do you aim to achieve this?

.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
Yes @SANJITH-KUMAR-20. We need to extract strings that are used for attribute names to the common package.

**Comment by SANJITH-KUMAR-20** [comment]
Maybe I can try working on this if you ellaborate a bit... Becasue I am new here and I haven't used openllmetry

**Comment by nirga** [comment]
@SANJITH-KUMAR-20 sure! If you look across the code you'll see many places where we [set an attribute by specifying its name](https://github.com/traceloop/openllmetry/blob/9f6048089c4de70cf6e43d19992fc088464ac8fe/packages/opentelemetry-instrumentation-pinecone/opentelemetry/instrumentation/pinecone/__init__.py#L81) instead of [using a constant](https://github.com/traceloop/openllmetry/blob/9f6048089c4de70cf6e43d19992fc088464ac8fe/packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/__init__.py#L122). We should purge them and move them all to constants [here](https://github.com/traceloop/openllmetry/blob/main/packages/opentelemetry-semantic-conventions-ai/opentelemetry/semconv/ai/__init__.py).

**Comment by SANJITH-KUMAR-20** [comment]
Oh ok I get it... I will look into it and will start working on this in a few days time!

**Comment by nirga** [comment]
Yes please!

**Comment by ArunimSamudra** [comment]
Thanks
