### ISSUE TITLE
🐛 Bug Report: warnings on LangChain

### ISSUE THREAD

**Issue by romeroej-inch** [traceloop/openllmetry#1171]
### Which component is this bug for?

OpenAI Instrumentation

### 📜 Description

You get random serializer errors when using openllmetry

Langchain 0.2.1
Traceloop-sdk 0.21

### 👟 Reproduction steps

Invoke LCEL chain if you have 

you need to have both metrics & regular exporter

 from azure.monitor.opentelemetry.exporter import AzureMonitorTraceExporter
 from azure.monitor.opentelemetry.exporter import AzureMonitorMetricExporter

    # Azure Exporter setup
    exporter = AzureMonitorTraceExporter(
        connection_string=APPLICATIONINSIGHTS_CONNECTION_STRING
    )
    metrics_exporter = AzureMonitorMetricExporter(
        connection_string=APPLICATIONINSIGHTS_CONNECTION_STRING
    )
Traceloop.init(
        app_name=f"fastapp",
        exporter=exporter,
        disable_batch=True,
        metrics_exporter=metrics_exporter,
    )

### 👍 Expected behavior

No failed messages

### 👎 Actual Behavior with Screenshots

Failed to execute process_request, error: Object of type ComplexPromptConfigModel is not JSON serializable
Failed to execute process_request, error: Object of type CallbackManagerForChainRun is not JSON serializable

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
Thanks @romeroej-inch! Which SDK version are you using?

**Comment by nirga** [comment]
@romeroej-inch any chance you can provide a snippet of what you were trying to run that generated these warnings? I want to reproduce it and make sure I've fixed it

**Comment by romeroej-inch** [comment]
It only happens when i use the initialization as in the bug description. My LCEL chains are ... pretty convoluted so im not able to share an actual example (im using a chain that calls a subchain but... like "manually" so its not very easy to snippet it).

I saw your commit, and looks like thats it.

**Comment by nirga** [comment]
Alright, closing this issue then
