### ISSUE TITLE
🚀 Feature: provide llm provider information in payload of metrics

### ISSUE THREAD

**Issue by jinsongo** [traceloop/openllmetry#1177]
### Which component is this feature for?

All Packages

### 🔖 Feature description

Since https://github.com/traceloop/openllmetry/pull/1121, I can no longer get the LLM service provider information from metric name, so I need to have the LLM service provider name from metrics payload, such as OpenAI, Watsonx and Anthropic.

For example, to add `"platform": "watsonx"`
```
{
    "resource_metrics": [
        {
            "resource": {
                "attributes": {
                    "telemetry.sdk.language": "python",
                    "telemetry.sdk.name": "opentelemetry",
                    "telemetry.sdk.version": "1.24.0",
                    "service.name": "traceloop-flow-watsonx-ai-0223",
                    "platform": "watsonx"
            },
```

### 🎤 Why is this feature needed ?

I need to display the LLM provider name with the metrics and aggregate the metrics per different LLM provider. 

### ✌️ How do you aim to achieve this?

I want to get the LLM provider information from Resource attributes of metrics payload.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by galkleinman** [comment]
Hi @jinsongo,

Thanks for reporting this one, and sorry for breaking it 🙈 .

I'll release a fix today.

**Comment by jinsongo** [comment]
@galkleinman, looks like the`gen_ai.system` can be used to identifiy AI product, I look forward to use it as soon as possible. Thanks.

**Comment by galkleinman** [comment]
@jinsongo I merged the fix yesterday. Sorry for the delay, I had some issues with flaky tests :)
