### ISSUE TITLE
🐛 Bug Report: Bump opentelemetry-instrumentation beta packages from 0.45b0 to 0.46b0

### ISSUE THREAD

**Issue by alfredoihernandez** [traceloop/openllmetry#1188]
### Which component is this bug for?

All Packages

### 📜 Description

All beta packages derived from https://github.com/open-telemetry/opentelemetry-python-contrib need to be updated from 0.45b0 to 0.46b0. Suggestion is to use wildcard, tilde, or greater than in toml files as opposed to caret for beta versions

### 👟 Reproduction steps

Attempt to install the following package versions:

opentelemetry-exporter-otlp = ">= 1.25.0"
opentelemetry-distro = ">= 0.46b0"
opentelemetry-instrumentation = ">= 0.46b0"
opentelemetry-instrumentation-langchain = ">= 0.21.1"
opentelemetry-instrumentation-openai = ">= 0.21.1"

### 👍 Expected behavior

Should be able to solve versioning for the latest opentelemetry-* packages 0.46b0

### 👎 Actual Behavior with Screenshots

0.822 Skipping virtualenv creation, as specified in config file.
1.163 Resolving dependencies...
15.90 
15.90 Because opentelemetry-instrumentation-openai (0.21.1) depends on opentelemetry-instrumentation (>=0.45b0,<0.46)
15.90  and no versions of opentelemetry-instrumentation-openai match >0.21.1, opentelemetry-instrumentation-openai (>=0.21.1) requires opentelemetry-instrumentation (>=0.45b0,<0.46).
15.90 So, because langserve-accelerator depends on both opentelemetry-instrumentation (>= 0.46b0) and opentelemetry-instrumentation-openai (>= 0.21.1), version solving failed.
------
failed to solve: process "/bin/sh -c poetry lock --no-update" did not complete successfully: exit code: 1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by nirga** [comment]
Thanks @alfredoihernandez, you're definitely right! Are you planning on submitting a PR?

**Comment by alfredoihernandez** [comment]
@nirga Yes I would love to! This is an urgent need for our team. Is it best to fork and merge upstream or can you grant me additional privileges?

**Comment by nirga** [comment]
Yes, fork and merge is the best approach. I'll make sure to merge and publish a version as soon as the PR is ready :)

**Comment by nirga** [comment]
@alfredoihernandez v0.21.2 is released
