### ISSUE TITLE
🐛 Bug Report: when using opentelemetry-collector send data to traceloop，it has error：missing port in address

### ISSUE THREAD

**Issue by commonfurture** [traceloop/openllmetry#1394]
### Which component is this bug for?

OpenAI Instrumentation

### 📜 Description

when using opentelemetry-collector send data to traceloop，it has error: 
grpc: addrConn.createTransport failed to connect to {Addr: "api.traceloop.com", ServerName: "api.traceloop.com", }. Err: connection error: desc = "transport: Error while dialing: dial tcp: address api.traceloop.com: missing port in address"	{"grpc_log": true}

### 👟 Reproduction steps

exporters:
  otlp/traceloop:
    endpoint: "api.traceloop.com"

### 👍 Expected behavior

grpc: addrConn.createTransport failed to connect to {Addr: "api.traceloop.com", ServerName: "api.traceloop.com", }. Err: connection error: desc = "transport: Error while dialing: dial tcp: address api.traceloop.com: missing port in address"	{"grpc_log": true}

### 👎 Actual Behavior with Screenshots

![image](https://github.com/traceloop/openllmetry/assets/37206678/b4ee87e1-8404-4907-8b15-5c2ce1b18592)

### 🤖 Python Version

3.9

### 📃 Provide any additional context for the Bug.

this is opentelemetry-collector config
![image](https://github.com/traceloop/openllmetry/assets/37206678/b56ee0a4-c6db-44f7-82a0-4844b27c39f5)

### 👀 Have you spent some time to check if this bug has been raised before?

- [ ] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
@commonfurture Hey! You should use `otlphttp` and not `otlp` since our endpoint expects HTTPS and not GRPC. I see now that our docs weren't reflecting that so we'll update them.
