### ISSUE TITLE
🚀 Feature: support embedding APIs for OpenAI

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry#14]
### Which component is this feature for?

OpenAI Instrumentation

### 🔖 Feature description

Support [OpenAI Embeddings API](https://github.com/openai/openai-cookbook/blob/main/examples/Get_embeddings.ipynb). Note that since outputs are extremely big, we probably shouldn't add them to a span, just the metadata

### 🎤 Why is this feature needed ?

Complete visibility into usage of LLMs

### ✌️ How do you aim to achieve this?

Similar to current instrumentation for chat / completion APIs

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by mohitk1995** [comment]
We want this feature to keep track of data related to model, Token usage, as part of the API request.
Something like:
engine, model, usage.

I think we should enable it by default. We could have an env variable to disable this. If this is not required by everyone.

**Comment by nirga** [comment]
Fixed with #335
