### ISSUE TITLE
🚀 Feature: Add OpenAI support for parallel tool calls

### ISSUE THREAD

**Issue by achang97** [traceloop/openllmetry#1427]
### Which component is this feature for?

OpenAI Instrumentation

### 🔖 Feature description

Turn `function_call` attribute into an array, to account for multiple/parallel function calls from OpenAI. In addition, include the tool call ID in each function object, which is used to distinguish between different function calls.

### 🎤 Why is this feature needed ?

Parallel function calls have been added to the OpenAI tool calling architecture.

### ✌️ How do you aim to achieve this?

Remove the assumption in the current implementation that there will always be exactly 1 tool call. Instead, iterate through the tool call array.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by nirga** [comment]
Fixed with #1424
