### ISSUE TITLE
🐛 Bug Report: OpenAI message doesn't account for `tool_calls`

### ISSUE THREAD

**Issue by achang97** [traceloop/openllmetry#1428]
### Which component is this bug for?

OpenAI Instrumentation

### 📜 Description

The current implementation assumes that every message has the `content` field. However, this is an unsafe assumption, as there can also be messages with just a `tool_calls` array.

### 👟 Reproduction steps

1. Add an input message with  `tool_calls` and no `content`

### 👍 Expected behavior

It should include `tool_calls` as a separate JSONified field.

### 👎 Actual Behavior with Screenshots

```
        "gen_ai.prompt.1.role": "user",
        "gen_ai.prompt.1.content": "Can you tell me the weather in San Francisco, CA?",

        # This should be a tool call. Instead, it just references the previous message.
        "gen_ai.prompt.2.role": "assistant",
        "gen_ai.prompt.2.content": "Can you tell me the weather in San Francisco, CA?",
```

### 🤖 Python Version

3.11.6

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by nirga** [comment]
Fixed with #1429
