### ISSUE TITLE
group dependabot to reduce spam

### ISSUE THREAD

**Issue by codefromthecrypt** [traceloop/openllmetry#1491]
As you maybe noticed, there have been a flood of dependabot commits, and these make it difficult to view the commit log or watch the repo without special filters.

I wonder if we can use grouping to rate-limit dependabot to one PR per day? That way, it is easier to follow for the more important change. Here's an example of such a change: https://github.com/wasilibs/go-re2/pull/122

**Comment by nirga** [comment]
Good idea, we'll definitely do that. There will still be significant amount of PRs I think since we can't group across packages (only several dependencies for the same package) and this repo already has 25 packages.
