### ISSUE TITLE
🐛 Bug Report: Streaming Tokens 

### ISSUE THREAD

**Issue by surajrl** [traceloop/openllmetry#165]
### Which component is this bug for?

OpenAI Instrumentation

### 📜 Description

I have an app running where I am streaming the tokens of my answers, streaming is working fine but when I initialize Traceloop using LlamaIndex the streaming features is disabled.

### 👟 Reproduction steps

1. Enable streaming in OpenAI
2. Initialize Traceloop in my applicaiton
3. Make a query

### 👍 Expected behavior

Streaming of tokens should still be working

### 👎 Actual Behavior with Screenshots

Tokens are not streamed.

### 🤖 Python Version

3.11.5

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
Thanks @surajrl! I've managed to reproduce this. Working on a solution

**Comment by surajrl** [comment]
> Thanks @surajrl! I've managed to reproduce this. Working on a solution

Great to hear! It would be nice if you could stream tokens whilst having Traceloop enabled, as I am planning on putting my app on production and streaming is a feature I definetly want to have, and it would be a shame not being able to use Traceloop at the same time. I hope you are able to find a solution! :)

**Comment by nirga** [comment]
@surajrl should work for you in v0.2.1 🎉

**Comment by surajrl** [comment]
> @surajrl should work for you in v0.2.1 🎉

It does! Thanks! Really impressed from solving it that fast ...
