### ISSUE TITLE
🚀 Feature: Tracing support for Amazon SageMaker endpoints

### ISSUE THREAD

**Issue by bobbywlindsey** [traceloop/openllmetry#1660]
### Which component is this feature for?

All Packages

### 🔖 Feature description

Add tracing support for [Amazon SageMaker endpoints](https://docs.aws.amazon.com/sagemaker/latest/dg/realtime-endpoints.html)

### 🎤 Why is this feature needed ?

Developers may deploy a variety of LLMs as endpoints on Amazon SageMaker. They'd query these endpoints using the [InvokeEndpoint](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_runtime_InvokeEndpoint.html) API to retrieve the LLM response.

### ✌️ How do you aim to achieve this?

1. Create `opentelemetry-instrumentation-sagemaker` package
2. Create instrumentation for the `sagemaker-runtime` service and patch the `invoke_endpoint` method.
3. Create span for the request.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by nirga** [comment]
Yes @bobbywlindsey! We've been wanting to do this for a while! I see that you want to work on this, let me know how can I help!
