### ISSUE TITLE
🚀 Feature: Support tool calling for Ollama

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry#1688]
### Which component is this feature for?

Ollama Instrumentation

### 🔖 Feature description

Support tool calling in Ollama Instrumentation:
https://github.com/ollama/ollama/blob/main/docs/api.md#chat-request-with-tools

### 🎤 Why is this feature needed ?

-

### ✌️ How do you aim to achieve this?

-

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
Yes @sathvikrav :)

**Comment by Karush2807** [comment]
is it still open for contribution?
