### ISSUE TITLE
🐛 Bug Report: incompatible opentelemetry-instrumentation==0.47b0 

### ISSUE THREAD

**Issue by cforce** [traceloop/openllmetry#1694]
### Which component is this bug for?

Anthropic Instrumentation

### 📜 Description

ERROR: Cannot install -r app/backend/requirements.txt (line 242), -r app/backend/requirements.txt (line 244), -r app/backend/requirements.txt (line 248), -r app/backend/requirements.txt (line 250), -r app/backend/requirements.txt (line 252), -r app/backend/requirements.txt (line 256), -r app/backend/requirements.txt (line 258 - opentelemetry-instrumentation-openai==0.26.0 ) and opentelemetry-instrumentation==0.47b0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

### 👟 Reproduction steps

pip install below requirements

#
# This file is autogenerated by pip-compile with Python 3.11
# by the following command:
#
#    pip-compile requirements.in
#
aiofiles==24.1.0
    # via quart
aiohttp==3.9.5
    # via
    #   -r requirements.in
    #   microsoft-kiota-authentication-azure
aiosignal==1.3.1
    # via aiohttp
annotated-types==0.7.0
    # via pydantic
anyio==4.4.0
    # via
    #   httpx
    #   openai
asgiref==3.8.1
    # via opentelemetry-instrumentation-asgi
attrs==23.2.0
    # via aiohttp
azure-ai-documentintelligence==1.0.0b3
    # via -r requirements.in
azure-cognitiveservices-speech==1.38.0
    # via -r requirements.in
azure-common==1.1.28
    # via azure-search-documents
azure-core==1.30.2
    # via
    #   azure-ai-documentintelligence
    #   azure-core-tracing-opentelemetry
    #   azure-identity
    #   azure-monitor-opentelemetry
    #   azure-monitor-opentelemetry-exporter
    #   azure-search-documents
    #   azure-storage-blob
    #   azure-storage-file-datalake
    #   microsoft-kiota-authentication-azure
    #   msrest
azure-core-tracing-opentelemetry==1.0.0b11
    # via azure-monitor-opentelemetry
azure-identity==1.17.1
    # via
    #   -r requirements.in
    #   msgraph-sdk
azure-monitor-opentelemetry==1.6.0
    # via -r requirements.in
azure-monitor-opentelemetry-exporter==1.0.0b27
    # via azure-monitor-opentelemetry
azure-search-documents==11.6.0b1
    # via -r requirements.in
azure-storage-blob==12.21.0
    # via
    #   -r requirements.in
    #   azure-storage-file-datalake
azure-storage-file-datalake==12.16.0
    # via -r requirements.in
beautifulsoup4==4.12.3
    # via -r requirements.in
blinker==1.8.2
    # via
    #   flask
    #   quart
certifi==2024.7.4
    # via
    #   httpcore
    #   httpx
    #   msrest
    #   requests
cffi==1.16.0
    # via cryptography
charset-normalizer==3.3.2
    # via requests
click==8.1.7
    # via
    #   flask
    #   quart
    #   uvicorn
cryptography==43.0.0
    # via
    #   -r requirements.in
    #   azure-identity
    #   azure-storage-blob
    #   msal
    #   pyjwt
    #   python-jose
deprecated==1.2.14
    # via opentelemetry-api
distro==1.9.0
    # via openai
ecdsa==0.19.0
    # via python-jose
fixedint==0.1.6
    # via azure-monitor-opentelemetry-exporter
flask==3.0.3
    # via quart
frozenlist==1.4.1
    # via
    #   aiohttp
    #   aiosignal
h11==0.14.0
    # via
    #   httpcore
    #   hypercorn
    #   uvicorn
    #   wsproto
h2==4.1.0
    # via
    #   httpx
    #   hypercorn
hpack==4.0.0
    # via h2
httpcore==1.0.5
    # via httpx
httpx[http2]==0.27.0
    # via
    #   microsoft-kiota-http
    #   msgraph-core
    #   openai
hypercorn==0.17.3
    # via quart
hyperframe==6.0.1
    # via h2
idna==3.7
    # via
    #   anyio
    #   httpx
    #   requests
    #   yarl
importlib-metadata==7.1.0
    # via
    #   opentelemetry-api
    #   opentelemetry-instrumentation-flask
isodate==0.6.1
    # via
    #   azure-ai-documentintelligence
    #   azure-search-documents
    #   azure-storage-blob
    #   azure-storage-file-datalake
    #   msrest
itsdangerous==2.2.0
    # via
    #   flask
    #   quart
jinja2==3.1.4
    # via
    #   flask
    #   quart
markupsafe==2.1.5
    # via
    #   jinja2
    #   quart
    #   werkzeug
microsoft-kiota-abstractions==1.3.3
    # via
    #   microsoft-kiota-authentication-azure
    #   microsoft-kiota-http
    #   microsoft-kiota-serialization-json
    #   microsoft-kiota-serialization-text
    #   msgraph-core
    #   msgraph-sdk
microsoft-kiota-authentication-azure==1.0.0
    # via
    #   msgraph-core
    #   msgraph-sdk
microsoft-kiota-http==1.3.2
    # via
    #   msgraph-core
    #   msgraph-sdk
microsoft-kiota-serialization-json==1.2.0
    # via msgraph-sdk
microsoft-kiota-serialization-text==1.0.0
    # via msgraph-sdk
msal==1.30.0
    # via
    #   -r requirements.in
    #   azure-identity
    #   msal-extensions
msal-extensions==1.2.0
    # via azure-identity
msgraph-core==1.1.2
    # via msgraph-sdk
msgraph-sdk==1.1.0
    # via -r requirements.in
msrest==0.7.1
    # via azure-monitor-opentelemetry-exporter
multidict==6.0.5
    # via
    #   aiohttp
    #   yarl
numpy==2.0.1
    # via -r requirements.in
oauthlib==3.2.2
    # via requests-oauthlib
openai==1.37.0
    # via
    #   -r requirements.in
    #   openai-messages-token-helper
openai-messages-token-helper==0.1.5
    # via -r requirements.in
opentelemetry-api==1.26.0
    # via
    #   azure-core-tracing-opentelemetry
    #   azure-monitor-opentelemetry-exporter
    #   microsoft-kiota-abstractions
    #   microsoft-kiota-authentication-azure
    #   microsoft-kiota-http
    #   opentelemetry-instrumentation
    #   opentelemetry-instrumentation-aiohttp-client
    #   opentelemetry-instrumentation-asgi
    #   opentelemetry-instrumentation-dbapi
    #   opentelemetry-instrumentation-django
    #   opentelemetry-instrumentation-fastapi
    #   opentelemetry-instrumentation-flask
    #   opentelemetry-instrumentation-httpx
    #   opentelemetry-instrumentation-openai
    #   opentelemetry-instrumentation-psycopg2
    #   opentelemetry-instrumentation-requests
    #   opentelemetry-instrumentation-urllib
    #   opentelemetry-instrumentation-urllib3
    #   opentelemetry-instrumentation-wsgi
    #   opentelemetry-sdk
    #   opentelemetry-semantic-conventions
opentelemetry-instrumentation==0.47b0
    # via
    #   opentelemetry-instrumentation-aiohttp-client
    #   opentelemetry-instrumentation-asgi
    #   opentelemetry-instrumentation-dbapi
    #   opentelemetry-instrumentation-django
    #   opentelemetry-instrumentation-fastapi
    #   opentelemetry-instrumentation-flask
    #   opentelemetry-instrumentation-httpx
    #   opentelemetry-instrumentation-openai
    #   opentelemetry-instrumentation-psycopg2
    #   opentelemetry-instrumentation-requests
    #   opentelemetry-instrumentation-urllib
    #   opentelemetry-instrumentation-urllib3
    #   opentelemetry-instrumentation-wsgi
opentelemetry-instrumentation-aiohttp-client==0.47b0
    # via -r requirements.in
opentelemetry-instrumentation-asgi==0.47b0
    # via
    #   -r requirements.in
    #   opentelemetry-instrumentation-fastapi
opentelemetry-instrumentation-dbapi==0.47b0
    # via opentelemetry-instrumentation-psycopg2
opentelemetry-instrumentation-django==0.47b0
    # via azure-monitor-opentelemetry
opentelemetry-instrumentation-fastapi==0.47b0
    # via azure-monitor-opentelemetry
-flask==1.26.0
    # via azure-monitor-opentelemetry
opentelemetry-instrumentation-httpx==0.47b0
    # via -r requirements.in
opentelemetry-instrumentation-openai==0.26.0
    # via -r requirements.in
opentelemetry-instrumentation-psycopg2==0.47b0
    # via azure-monitor-opentelemetry
opentelemetry-instrumentation-requests==0.47b0
    # via
    #   -r requirements.in
    #   azure-monitor-opentelemetry
opentelemetry-instrumentation-urllib==0.47b0
    # via azure-monitor-opentelemetry
opentelemetry-instrumentation-urllib3==0.47b0
    # via azure-monitor-opentelemetry
opentelemetry-instrumentation-wsgi==0.47b0
    # via
    #   opentelemetry-instrumentation-django
    #   opentelemetry-instrumentation-flask
opentelemetry-resource-detector-azure==0.1.5
    # via azure-monitor-opentelemetry
opentelemetry-sdk==1.26.0
    # via
    #   azure-monitor-opentelemetry
    #   azure-monitor-opentelemetry-exporter
    #   microsoft-kiota-abstractions
    #   microsoft-kiota-authentication-azure
    #   microsoft-kiota-http
    #   opentelemetry-resource-detector-azure
opentelemetry-semantic-conventions==0.47b0
    # via
    #   opentelemetry-instrumentation-aiohttp-client
    #   opentelemetry-instrumentation-asgi
    #   opentelemetry-instrumentation-dbapi
    #   opentelemetry-instrumentation-django
    #   opentelemetry-instrumentation-fastapi
    #   opentelemetry-instrumentation-flask
    #   opentelemetry-instrumentation-httpx
    #   opentelemetry-instrumentation-openai
    #   opentelemetry-instrumentation-requests
    #   opentelemetry-instrumentation-urllib
    #   opentelemetry-instrumentation-urllib3
    #   opentelemetry-instrumentation-wsgi
    #   opentelemetry-sdk
#opentelemetry-semantic-conventions-ai==0.3.6
    # via opentelemetry-instrumentation-openai
opentelemetry-util-http==0.47b0
    #   opentelemetry-instrumentation-aiohttp-client
    #   opentelemetry-instrumentation-asgi
    #   opentelemetry-instrumentation-django
    #   opentelemetry-instrumentation-fastapi
    #   opentelemetry-instrumentation-flask
    #   opentelemetry-instrumentation-httpx
    #   opentelemetry-instrumentation-requests
    #   opentelemetry-instrumentation-urllib
    #   opentelemetry-instrumentation-urllib3
    #   opentelemetry-instrumentation-wsgi
packaging==24.1
    # via opentelemetry-instrumentation-flask
pendulum==3.0.0
    # via microsoft-kiota-serialization-json
pillow==10.4.0
    # via
    #   -r requirements.in
    #   openai-messages-token-helper
portalocker==2.10.1
    # via msal-extensions
priority==2.0.0
    # via hypercorn
psutil==5.9.8
    # via azure-monitor-opentelemetry-exporter
pyasn1==0.6.0
    # via
    #   python-jose
    #   rsa
pycparser==2.22
    # via cffi
pydantic==2.8.2
    # via openai
pydantic-core==2.20.1
    # via pydantic
pyjwt[crypto]==2.8.0
    # via
    #   msal
    #   pyjwt
pymupdf==1.24.7
    # via -r requirements.in
pymupdfb==1.24.6
    # via pymupdf
pypdf==4.3.1
    # via -r requirements.in
python-dateutil==2.9.0.post0
    # via
    #   microsoft-kiota-serialization-text
    #   pendulum
    #   time-machine
python-jose[cryptography]==3.3.0
    # via -r requirements.in
quart==0.19.6
    # via
    #   -r requirements.in
    #   quart-cors
quart-cors==0.7.0
    # via -r requirements.in
regex==2024.5.15
    # via tiktoken
requests==2.32.3
    # via
    #   azure-core
    #   msal
    #   msrest
    #   requests-oauthlib
    #   tiktoken
requests-oauthlib==2.0.0
    # via msrest
rsa==4.9
    # via python-jose
six==1.16.0
    # via
    #   azure-core
    #   ecdsa
    #   isodate
    #   python-dateutil
sniffio==1.3.1
    # via
    #   anyio
    #   httpx
    #   openai
soupsieve==2.5
    # via beautifulsoup4
std-uritemplate==1.0.3
    # via microsoft-kiota-abstractions
tenacity==8.5.0
    # via -r requirements.in
tiktoken==0.7.0
    # via
    #   -r requirements.in
    #   openai-messages-token-helper
    #   opentelemetry-instrumentation-openai
time-machine==2.14.2
    # via pendulum
tqdm==4.66.4
    # via openai
types-beautifulsoup4==4.12.0.20240511
    # via -r requirements.in
types-html5lib==1.1.11.20240228
    # via types-beautifulsoup4
types-pillow==10.2.0.20240520
    # via -r requirements.in
types-pyasn1==0.6.0.20240402
    # via types-python-jose
types-python-jose==3.3.4.20240106
    # via -r requirements.in
typing-extensions==4.12.2
    # via
    #   azure-ai-documentintelligence
    #   azure-core
    #   azure-identity
    #   azure-storage-blob
    #   azure-storage-file-datalake
    #   openai
    #   opentelemetry-sdk
    #   pydantic
    #   pydantic-core
tzdata==2024.1
    # via pendulum
urllib3==2.2.2
    # via requests
uvicorn==0.30.3
    # via -r requirements.in
werkzeug==3.0.3
    # via
    #   flask
    #   quart
wrapt==1.16.0
    # via
    #   deprecated
    #   opentelemetry-instrumentation
    #   opentelemetry-instrumentation-aiohttp-client
    #   opentelemetry-instrumentation-dbapi
    #   opentelemetry-instrumentation-urllib3
wsproto==1.2.0
    # via hypercorn
yarl==1.9.4
    # via aiohttp
zipp==3.19.2
    # via importlib-metadata

# The following packages are considered to be unsafe in a requirements file:
# setuptools

### 👍 Expected behavior

It should be compatible

### 👎 Actual Behavior with Screenshots

be compatible

### 🤖 Python Version

3.11

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
Thanks @cforce! Bumping now
