### ISSUE TITLE
🚀 Feature: support structured outputs for OpenAI

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry#1815]
### Which component is this feature for?

OpenAI Instrumentation

### 🔖 Feature description

Add support to OpenAI's recently announced structured outputs:
https://openai.com/index/introducing-structured-outputs-in-the-api/
For example, support `refusal` responses

### 🎤 Why is this feature needed ?

-

### ✌️ How do you aim to achieve this?

-

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by Benedikt-Wolf** [comment]
I'll have a look at it

**Comment by iarslankhalid** [comment]
> I'll have a look at it, if no one is working on this currently?

hey @Benedikt-Wolf, is there any update regarding this feature?

**Comment by Benedikt-Wolf** [comment]
Hey @iarslankhalid no, not at all😅I am in a bit of a stress rn (last exam, job interviews, ...), so if u want to take over, please do so 👍 I will probably not have time in the next 2 weeks

**Comment by iarslankhalid** [comment]
sure @Benedikt-Wolf .. Good luck with your exams and job interviews

**Comment by vinit5112** [comment]
@nirga I will look at it, if no one is working on this currently?

**Comment by nirga** [comment]
Sure @vinit5112 :)

**Comment by vinit5112** [comment]
@nirga, I understood the issue. But can you help me where we need to structure openai output.

**Comment by nirga** [comment]
Hey @vinit5112 sorry for thte delay I was OOO!
We need to log the data returned by the structured output as OpenAI describes in this link:
https://openai.com/index/introducing-structured-outputs-in-the-api/

For example, they return something like `refusal` which we don't log on the span currently

**Comment by nirga** [comment]
Thanks @AnsariZayd! Not sure where @vinit5112 stands with this

**Comment by AnsariZayd** [comment]
Hi Nir, Thanks for giving me this opportunity. I am a little confused about
what exactly the new feature is intended to do, it would be great if you
can provide me some details related to the feature. Also I was looking at
the code in the packages/opentelemetry-instrumentation-openai, I am not
sure where do you want to add the new feature. Do you want to add a new
folder or file for this feature and wanted to store the refusal in a new
log ? Please let me know so that I can start working on it.
regards,
Zayd

**Comment by nirga** [comment]
@AnsariZayd have you looked at this comment? https://github.com/traceloop/openllmetry/issues/1815#issuecomment-2353198528

**Comment by AnsariZayd** [comment]
OK I got it.

**Comment by Karush2807** [comment]
is it still open for contribution?

**Comment by nirga** [comment]
Hey @Karush2807 any open issue here is open for contribution :)
