### ISSUE TITLE
🚀 Feature: Support Prompt Caching

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry#1838]
### Which component is this feature for?

Anthropic Instrumentation

### 🔖 Feature description

Support logging of prompt caching, including cached token usage:

https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching#how-can-i-track-the-effectiveness-of-my-caching-strategy

### 🎤 Why is this feature needed ?

-

### ✌️ How do you aim to achieve this?

-

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by samsmithspace** [comment]
Hi @nirga, can I work on this task?

**Comment by nirga** [comment]
Yes! Thank you :) @samsmithspace

**Comment by kowshik24** [comment]
Hi @samsmithspace  are you still working on it?

**Comment by kowshik24** [comment]
Hi @nirga I have updated the prompt caching. Could you please check?

**Comment by Karush2807** [comment]
is it still open for contribution?

**Comment by nirga** [comment]
@dinmukhamedm this is fixed with #2175 right?
