### ISSUE TITLE
Feature: OpenTelemetry Metrics for AWS Bedrock

### ISSUE THREAD

**Issue by gyliu513** [traceloop/openllmetry#1875]
### Which component is this feature for?

Bedrock Instrumentation

### 🔖 Feature description

This is a sub task for #251 to support AWS Bedrock

### 🎤 Why is this feature needed ?

This is a sub task for #251 to support AWS Bedrock

### ✌️ How do you aim to achieve this?

This is a sub task for #251 to support AWS Bedrock

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by gyliu513** [comment]
@jinsongo ^^

**Comment by pradyutsingh** [comment]
Can I work on this? If it's not already picked up.

**Comment by jinsongo** [comment]
@pradyutsingh I am working on that ^_^

**Comment by pradyutsingh** [comment]
Ohh, no worries. I'll pickup something else then.

**Comment by gyliu513** [comment]
@pradyutsingh For metrics collection, I think only Watsonx, OpenAI, Anthropic support now, and @jinsongo is working for bedrock, you can probably open issues for other llm providers if you want, good luck and thanks for your help here!

**Comment by jinsongo** [comment]
I submitted a PR  https://github.com/traceloop/openllmetry/pull/1957 and set its status to draft until all necessary tests are passed

**Comment by CallSohail** [comment]
I want to work on this issue.

**Comment by gyliu513** [comment]
Oh, thanks @CallSohail , this issue has been fixed, let me close this one. I think you can grab some other issues now :)
