### ISSUE TITLE
🐛 Bug Report: I have been charged $100 by traceloop

### ISSUE THREAD

**Issue by bhattbhuwan13** [traceloop/openllmetry#1903]
### Which component is this bug for?

Anthropic Instrumentation

### 📜 Description

I had subscribed to a $0 plan but my account was deducted by $100 today. How can I claim the refund? I haven't used traceloop for anything except testing. I doubt I have incurred any cost.

<img width="1285" alt="Screenshot 2024-08-28 at 20 32 04" src="https://github.com/user-attachments/assets/b3a8125b-165c-4d27-afb6-2c75c5b1bc08">

I can provide the payment details as well. 

I used my google account to sign up for traceloop: bbhattanepal@gmail.com

I didn't get any email prior to getting the money deducted.

### 👟 Reproduction steps

-

### 👍 Expected behavior

-

### 👎 Actual Behavior with Screenshots

-

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by bhattbhuwan13** [comment]
What is the contact email for the support team?

**Comment by galkleinman** [comment]
Hey @bhattbhuwan13, 

If that's the case, we'll definitely make sure that you'll be refunded.

Feel free to contact us through our support widget in our website, or through our community slack. (You can also message me directly there - Gal Kleinman).

**Comment by galkleinman** [comment]
@bhattbhuwan13 no need to contact. I found your transaction, and refunded it. 
It make take few days to see the refund in your account.

Still, feel free to contact us for any further issue. 

Closing the github issue here.
