### ISSUE TITLE
🚀 Feature: upgrade opentelemetry-python-contrib deps to 1.27.0/0.48b0

### ISSUE THREAD

**Issue by tianjianjiang** [traceloop/openllmetry#1904]
### Which component is this feature for?

All Packages

### 🔖 Feature description

About 10 hours ago https://github.com/open-telemetry/opentelemetry-python-contrib.git released a new version that fixed gRPC compatibility issues. It seems to safe to upgrade according to the changelog https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CHANGELOG.md, and being gRPC-compatible indirectly will be greatly appreciated even when openllmetry doesn't need gRPC.

### 🎤 Why is this feature needed ?

Otherwise I cannot upgrade `opentelemetry-instrumentation-grpc` to 0.48b0 while using openllmetry packages like `opentelemetry-instrumentation-openai` due to its `^0.47b0` constraint.

### ✌️ How do you aim to achieve this?

Change every pyproject.toml and rebuild each poetry.lock, e.g., https://github.com/traceloop/openllmetry/pull/1695

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by galkleinman** [comment]
Thanks for submitting this one @tianjianjiang.

I'll issue a pull request bumping this one either later today or tomorrow. 

In the meantime, feel free to submit such PR yourself and i'll review it :)

**Comment by galkleinman** [comment]
@tianjianjiang I released version 0.29.0 which contains the relevant dependency upgrades (PR: https://github.com/traceloop/openllmetry/pull/1905).

LMK if everything works for you now or if you need any further assistance.

**Comment by tianjianjiang** [comment]
@galkleinman Much obliged! Auto-instrumented traces and metrics work nicely. 🙇👍🖖

**Comment by galkleinman** [comment]
Glad to assist :)
