### ISSUE TITLE
🐛 Bug Report: Metrics wasn't sent when use chatmodel (openai , chatopenai ) from langchain

### ISSUE THREAD

**Issue by ThanawaratGithub** [traceloop/openllmetry#1912]
### Which component is this bug for?

Langchain Instrumentation

### 📜 Description

When I use OpenAI or ChatOpenAI from the Langchain_OpenAI library for normal tasks, there is no issue with spans, but the metrics are not being sent to my Prometheus. However, if I use OpenAI directly, it works without any problems.

### 👟 Reproduction steps

It should have some metrics come out after running this code. But it didn't.
```
from langchain_openai import OpenAI

llm = OpenAI()


from langchain_core.prompts import PromptTemplate

prompt = PromptTemplate.from_template("How to say {input} in {output_language}:\n")

chain = prompt | llm
chain.invoke(
    {
        "output_language": "German",
        "input": "I love programming.",
    }
)


```

### 👍 Expected behavior

it should have metrics as usual.

### 👎 Actual Behavior with Screenshots

from above code I can't see any metrics was sent from that 

### 🤖 Python Version

3.11

### 📃 Provide any additional context for the Bug.

I sent it to Prometheus

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ThanawaratGithub** [comment]
@dosu I didn't see any error messages when I run the code it. I just normally use Traceloop.init() and It work with openai but not langchain.

**Comment by ThanawaratGithub** [comment]
@dosu here Traceloop.init(
    app_name=os.getenv('OTEL_SERVICE_NAME'),
    api_endpoint=os.getenv('OTEL_EXPORTER_OTLP_ENDPOINT'),
)

**Comment by ThanawaratGithub** [comment]
@dosu yes I confirm. and no error.

**Comment by nirga** [comment]
Thanks @ThanawaratGithub and sorry for the dosu bot 😅
It's a new tool we've been trying

**Comment by ThanawaratGithub** [comment]
Mo worry. Im having fun talking with dosu.

**Comment by ThanawaratGithub** [comment]
Could you please point me out which function is responsible for sending metrics when I use langchain?

**Comment by nirga** [comment]
@ThanawaratGithub sorry for the delay here, I was OOO :) 
It's a bit complicated, we can hop on a call if needed.
Basically, [this](https://github.com/traceloop/openllmetry/blob/main/packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py) is where we log stuff from langchain.
And [this](https://github.com/traceloop/openllmetry/blob/b91d7176e66382e5ba439c23a1ce32b4576fc940/packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py#L374) is how metrics are created in other instrumentations, which we need to do probably [here](https://github.com/traceloop/openllmetry/blob/main/packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/__init__.py) as well. Then, we can log them in the [langchain callback](https://github.com/traceloop/openllmetry/blob/main/packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py) similar to [here](https://github.com/traceloop/openllmetry/blob/b91d7176e66382e5ba439c23a1ce32b4576fc940/packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py#L261).

Hope that makes sense :)

**Comment by nitin302** [comment]
I'm seeing the same issue azure openai + langchain as well (from langchain_openai import AzureChatOpenAI). There are no metrics sent.

**Comment by nirga** [comment]
Thanks for reporting @nitin302! We're open for contributions on this and we'll try to prioritize a fix!

**Comment by nitin302** [comment]
Could you please check this - https://github.com/traceloop/openllmetry/pull/2154#issuecomment-2418772694

**Comment by nirga** [comment]
@nitin302 already opened #2166 :)
