### ISSUE TITLE
🚀 Feature: Pydantic v2 upgrade

### ISSUE THREAD

**Issue by grski** [traceloop/openllmetry#193]
### Which component is this feature for?

All Packages

### 🔖 Feature description

Could you please update pydantic to v2? 

### 🎤 Why is this feature needed ?

Version resolving fails if any of the packages has a contstraint for >2 eg. pydantic-settings.

Because no versions of traceloop-sdk match >0.3.0,<0.4.0
 and traceloop-sdk (0.3.0) depends on pydantic (>=1.10.12,<2.0.0), traceloop-sdk (>=0.3.0,<0.4.0) requires pydantic (>=1.10.12,<2.0.0).
And because pydantic-settings (2.0.3) depends on pydantic (>=2.0.1)
 and no versions of pydantic-settings match >2.0.3,<3.0.0, traceloop-sdk (>=0.3.0,<0.4.0) is incompatible with pydantic-settings (>=2.0.3,<3.0.0).
So, because theydo-journey-ai depends on both pydantic-settings (^2.0.3) and traceloop-sdk (^0.3.0), version solving failed.

### ✌️ How do you aim to achieve this?

It'll need some work probably.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by nirga** [comment]
Thanks @grski! We actually were in pydantic 2 and downgraded because Haystack requires v1 (https://github.com/deepset-ai/haystack/issues/5304). Since we have issues in haystack regardless and the automatic instrumentation is now disabled (you can just install it manually) - let's upgrade to v2

**Comment by grski** [comment]
That'd be amazing!

**Comment by galkleinman** [comment]
Thanks for raising this one @grski. As @nirga mentioned, it was on purpose, since Haystack currently dictates `pydantic<2`.

Discussing it internally, and since Haystack auto-instrumentation is currently disabled anyway we've decided to bump pydantic to 2.5.0 as suggested in the issue.

Version `0.3.1` is now published, and the issue should be resolved there 😃

**Comment by grski** [comment]
Lovely, tahnk you very much @galkleinman @nirga
