### ISSUE TITLE
🚀 Feature: Use usage attribute instead of anthropic.count_tokens()

### ISSUE THREAD

**Issue by coffecup25** [traceloop/openllmetry#2061]
### Which component is this feature for?

Anthropic Instrumentation

### 🔖 Feature description

Getting more accurate numbers on token usage, including the token cost of images, by using the usage attribute from the anthropic response.

### 🎤 Why is this feature needed ?

The description of the function says that the function is only accurate for older models such as Claude 2.1. I think the majority of people use the later 3.X models for which this function gives a very rough estimate. Anthropic say that the usage attribute on the response should be used instead.

```python
def count_tokens(
        self,
        text: str,
    ) -> int:
        """Count the number of tokens in a given string.

        Note that this is only accurate for older models, e.g. `claude-2.1`. For newer
        models this can only be used as a _very_ rough estimate, instead you should rely
        on the `usage` property in the response for exact counts.
        """
        # Note: tokenizer is untyped
        tokenizer = self.get_tokenizer()
        encoded_text = tokenizer.encode(text)  # type: ignore
        return len(encoded_text.ids)  # type: ignore
```

### ✌️ How do you aim to achieve this?

Update the anthropic instrumentation to use the token count from the usage attribute of the response instead of calling the count_token function.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by sahil9001** [comment]
Can you please assign this to me @coffecup25 ?

**Comment by coffecup25** [comment]
@sahil9001 Doesn't seem like I can do that. You probably have to talk with one of the maintainers of the repo.
