### ISSUE TITLE
🐛 Bug Report: With workflow/task annotation, failed trace will not able to send to backend

### ISSUE THREAD

**Issue by gyliu513** [traceloop/openllmetry#2076]
### Which component is this bug for?

Anthropic Instrumentation

### 📜 Description

I was using workflow/task for this example https://github.com/gyliu513/langX101/blob/main/aws/react-bedrock3.py#L141, if I was using a bad AWS key, then there will be no tracing sending to backend.

### 👟 Reproduction steps

Run https://github.com/gyliu513/langX101/blob/main/aws/react-bedrock3.py#L141 with a bad AWS key

### 👍 Expected behavior

Backend should able to capture some errors if the AI Application has some errors with workflow/task annotation.

### 👎 Actual Behavior with Screenshots

I was using IBM instana for a test, and there is no metrics when using a bad AWS key

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jinsongo** [comment]
According to investigation, with workflow/task annotation, the span of `workflow` will be lost if trace failed, but the span of `bedrock.completion` still retain the parent_id pointing to `workflow`, that causes problem.
