### ISSUE TITLE
🐛 Bug Report: Google Instrumentation does not work

### ISSUE THREAD

**Issue by coffecup25** [traceloop/openllmetry#2140]
### Which component is this bug for?

Traceloop SDK

### 📜 Description

The python sdk does not instrument the calls when using the google_generativeai sdk. However when manually calling the instrumentation like this:

```python
from opentelemetry.instrumentation.google_generativeai import GoogleGenerativeAiInstrumentor

GoogleGenerativeAiInstrumentor().instrument()
```

The calls are correctly added to the trace.

### 👟 Reproduction steps

The example code doesn't work from the traceloop website doesn't work.  

```python
import google.generativeai as genai
from traceloop.sdk import Traceloop
from traceloop.sdk.decorators import workflow
from traceloop.sdk.instruments import Instruments

import os 
import dotenv

dotenv.load_dotenv(dotenv.find_dotenv())
Traceloop.init(app_name="joke_generation_service", instruments={Instruments.GOOGLE_GENERATIVEAI})


genai.configure(api_key=os.environ.get("GENAI_API_KEY"))

@workflow(name="joke_creation")
def create_joke():
    model = genai.GenerativeModel("gemini-1.0-pro-latest")
    response = model.generate_content(
        "Give me ten interview questions for the role of program manager.",
    )

    return response.text

print(create_joke())
```

### 👍 Expected behavior

The instrumentation should automatically work instead of having to manually initialise it.

### 👎 Actual Behavior with Screenshots

The calls using the google_generativeai calls didn't show up in my Grafana Tempo until I started the instrumentor from opentelementry manually

### 🤖 Python Version

3.12

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
@coffecup25 sorry for taking too long here - fix is on the way!
