### ISSUE TITLE
🐛 Bug Report: Adding asyncio.run() in 0.31.3 makes the package fail when run from within async

### ISSUE THREAD

**Issue by jp-agenta** [traceloop/openllmetry#2195]
### Which component is this bug for?

All Packages

### 📜 Description

Calling `openai` endpoints from within an `async` function works in `0.31.2` but fails starting in `0.31.3` since `asyncio.run()` was added.

### 👟 Reproduction steps

1. add `openai` instrumentation
2. add a call to an `openai` endpoint inside an `async` function

```
async def foo(input):
    
    ...
    result = openai.embeddings.create(input=input, model="text-embedding-ada-002")
    ...

    return result
```

### 👍 Expected behavior

3.a. test in `0.31.2` -> success
3.b. test in `0.31.3` -> success

### 👎 Actual Behavior with Screenshots

3.a. test in `0.31.2` -> success
3.b. test in `0.31.3` -> failure

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
Thanks for reporting @jp-agenta! Can you verify this bug exists with the latest version? (v0.33.2)

**Comment by jp-agenta** [comment]
Hi @nirga, thanks for your quick response.
I will try again with `0.33.2` as soon as practicable and I will get back to you soon !

**Comment by mmabrouk** [comment]
> Thanks for reporting @jp-agenta! Can you verify this bug exists with the latest version? (v0.33.2)

Hi @nirga , I confirm that the bug still exists in v0.33.2

```
  File "...opentelemetry/instrumentation/openai/utils.py", line 78, in wrapper
    return func(
  File "...opentelemetry/instrumentation/openai/shared/chat_wrappers.py", line 81, in chat_wrapper
    asyncio.run(_handle_request(span, kwargs, instance))
  File ".../asyncio/runners.py", line 33, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop
sys:1: RuntimeWarning: coroutine '_handle_request' was never awaited
```

**Comment by nirga** [comment]
@mmabrouk thanks! do you happen to have a small demo that reproduces this?

**Comment by mmabrouk** [comment]
Yes of course:

```
from opentelemetry.instrumentation.openai import OpenAIInstrumentor
from openai import OpenAI
import asyncio
openai = OpenAI()


OpenAIInstrumentor().instrument()


async def openai_workflow(topic: str, genre: str):
    response = openai.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": f"Write a short {genre} story about {topic}."},
        ],
    )

    return response.choices[0].message.content

if __name__ == "__main__":
    asyncio.run(openai_workflow(topic="test", genre="test"))

```

The output:

```
Traceback (most recent call last):
  File ".../example.py", line 22, in <module>
    asyncio.run(openai_workflow(topic="test", genre="test"))
  File ".../python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File ".../python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File ".../example.py", line 11, in
    response = openai.chat.completions.create(
  File ".../python3.9/site-packages/opentelemetry/instrumentation/openai/utils.py", line 78, in wrapper
    return func(
  File ".../python3.9/site-packages/opentelemetry/instrumentation/openai/shared/chat_wrappers.py", line 81, in chat_wrapper
    asyncio.run(_handle_request(span, kwargs, instance))
  File ".../python3.9/asyncio/runners.py", line 33, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop
sys:1: RuntimeWarning: coroutine '_handle_request' was never awaited
```

**Comment by mmabrouk** [comment]
The issue seems to be introduced in [this PR](https://github.com/traceloop/openllmetry/pull/2051/files)

Adding this line seems to have created this issue: https://github.com/traceloop/openllmetry/blob/c18fb76de7be510c9dbede543c6a124d60b81c22/packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py#L81

I would consider this bug as critical. Since, after the change, instrumenting any OpenAI call within an async FastAPI route would not work.
