### ISSUE TITLE
🚀 Feature: Introduce instrumentation for litellm

### ISSUE THREAD

**Issue by gyliu513** [traceloop/openllmetry#2196]
### Which component is this feature for?

All Packages

### 🔖 Feature description

CrewAI uses either Langchain or LiteLLM under the hood to call models, depending on the version.

 CrewAI<0.63.0 using Langchain while CrewAI>= 0.63.0 using litellm.

OpenLLMetry already support instrumentation for langchain, but not for litellm yet, if we can introduce litellm support, then openLLMetry will able to support observability for CrewAI with any versions.

### 🎤 Why is this feature needed ?

This is required by CrewAI Observability.

### ✌️ How do you aim to achieve this?

Introduce new instrumentation for LiteLLM.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by gyliu513** [comment]
@nirga ^^

**Comment by nirga** [comment]
We already support LiteLLM! https://docs.litellm.ai/docs/observability/opentelemetry_integration

**Comment by gyliu513** [comment]
My bad, I think I used to demo this feature before internally in IBM, thanks @nirga 👍
