### ISSUE TITLE
🐛 Bug Report: pip conflicts

### ISSUE THREAD

**Issue by TaylorN15** [traceloop/openllmetry#2272]
### Which component is this bug for?

OpenAI Instrumentation

### 📜 Description

The latest version of the OpenAI instrumentation seems to conflict with all the other new versions of the OT instrumentation libraries.

I haven't tested, but you should be able to update the [toml](https://github.com/traceloop/openllmetry/blob/076ad93e615f9e46c9c99e324f47a9282e773516/packages/opentelemetry-instrumentation-openai/pyproject.toml#L28) with

`opentelemetry-instrumentation = ">=0.48b0, <0.50.0"`

### 👟 Reproduction steps

Install these packages
```
opentelemetry-instrumentation-aiohttp-client==0.49b0
opentelemetry-instrumentation-httpx==0.49b0
opentelemetry-instrumentation-requests==0.49b0
opentelemetry-instrumentation-openai==0.33.9
```

### 👍 Expected behavior

Should work with OT 0.49b0

### 👎 Actual Behavior with Screenshots

ERROR: Cannot install -r req_test.txt (line 2), -r req_test.txt (line 3), -r req_test.txt (line 4) and -r req_test.txt (line 5) because these package versions have conflicting dependencies.

The conflict is caused by:
    opentelemetry-instrumentation-aiohttp-client 0.49b0 depends on opentelemetry-instrumentation==0.49b0
    opentelemetry-instrumentation-httpx 0.49b0 depends on opentelemetry-instrumentation==0.49b0
    opentelemetry-instrumentation-requests 0.49b0 depends on opentelemetry-instrumentation==0.49b0
    opentelemetry-instrumentation-openai 0.33.9 depends on opentelemetry-instrumentation<0.49 and >=0.48b0

### 🤖 Python Version

3.12

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by TaylorN15** [comment]
> A similar issue was previously reported and resolved regarding incompatible versions of `opentelemetry-instrumentation` [[1]](https://github.com/traceloop/openllmetry/issues/1694). The issue was closed by a pull request that updated the dependency to a compatible version.

This was several months ago, the same issue has occurred again...

**Comment by dinmukhamedm** [comment]
+1 on this, noticed this yesterday.

I think this might be a good time (or even a requirement) to also update the following to `1.28.0`:

```
opentelemetry-api
opentelemetry-sdk
opentelemetry-exporter-otlp-proto-http
opentelemetry-exporter-otlp-proto-grpc
```

**Comment by nirga** [comment]
I need to remove dosu - not super helpful :/
Thanks @TaylorN15 and @dinmukhamedm  I'll bump versions today. We'll need to make something to do that automatically on otel version releas.
