### ISSUE TITLE
🚀 Feature:  How to use opentelemetry-instrumentation-langchain

### ISSUE THREAD

**Issue by gigi1121** [traceloop/openllmetry#229]
### Which component is this feature for?

Anthropic Instrumentation

### 🔖 Feature description

I have backend opentelemetry-server, how to use opentelemetry-instrumentation-langchain to collector our langchain tracing

### 🎤 Why is this feature needed ?

I can see opentelemetry-instrumentation-langchain  , but not found readme

### ✌️ How do you aim to achieve this?

use our langchain project

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
Hey! Fixed this in #230 and also added [docs about how to do it](https://www.traceloop.com/docs/openllmetry/tracing/without-sdk)
