### ISSUE TITLE
🐛 Bug Report: OpenAI Assistant API instrumentation doesn't use token stats from response

### ISSUE THREAD

**Issue by dinmukhamedm** [traceloop/openllmetry#2318]
### Which component is this bug for?

OpenAI Instrumentation

### 📜 Description

OpenAI Assistant API instrumentation does not use the token usage that one could get from the `run.usage` object. In addition, `gen_ai.system=openai` is not sent

### 👟 Reproduction steps

1. Use [sample app](https://github.com/traceloop/openllmetry/blob/main/packages/sample-app/sample_app/openai_assistant.py) to call an Assistant.
2. [Optional] add `print(run.usage)` after line 34, when `run.status == "completed"`.

### 👍 Expected behavior

- The resulting span must contain `gen_ai.system = openai` in its attributes.
- Tokens must be added as `gen_ai.usage` attributes even when `enrich_tokens` flag is not set, because they are returned in the response.

### 👎 Actual Behavior with Screenshots

- The resulting span does not have the system attribute
- There are no `gen_ai.usage.*_tokens` attributes on the resulting span

### 🤖 Python Version

3.9

### 📃 Provide any additional context for the Bug.

(I haven't tried with the token enricher/in-place counter, but I think we should not rely on it, now that the API returns token usage)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by nirga** [comment]
Thanks for reporting @dinmukhamedm! Looking forward for the fix 🙏
