### ISSUE TITLE
🚀 Feature: Replicate Instrumentation

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry#242]
### Which component is this feature for?

All Packages

### 🔖 Feature description

Instrument calls to [Replicate](https://replicate.com/docs/get-started/python), including adding attributes for input parameters, model, etc. - similarly to our [Anthropic](https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-anthropic) instrumentation. The instrumentation should support all types of calls - streaming, non streaming, async, etc.

### 🎤 Why is this feature needed ?

Completeness of OpenLLMetry

### ✌️ How do you aim to achieve this?

Similar to other instrumentations we have in this repo.

### 🔄️ Additional Information

* Make sure to initialize this in [Traceloop SDK](https://github.com/traceloop/openllmetry/blob/main/packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py#L241).
* Add proper [tests](https://github.com/traceloop/openllmetry/tree/main/packages/traceloop-sdk/tests).

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by Min2who** [comment]
can i get assigned?
