### ISSUE TITLE
Combine workflow and aworkflow (and Other Annotations)

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry#2434]
OpenLLMetry currently separates annotations for synchronous and asynchronous functions (e.g., `@workflow` and `@aworkflow`). This approach introduces redundancy and complexity. We propose unifying these into single, flexible decorators (e.g., `@workflow`) that handle both sync and async functions seamlessly. This change should extend to all annotations with similar patterns.

Proposed Changes:
	1.	Create unified decorators for `@workflow`, `@task`, and similar annotations.
	2.	Enhance internal logic to automatically detect and handle function types.
	3.	Update annotations documentation with clear examples.
	4.	Deprecate old annotations with migration guidance.

Tasks:
	•	Design and implement unified decorators.
	•	Update tests and documentation for all affected annotations.
	•	Deprecate old annotations with clear migration steps.

Benefits:
Streamlines API usage across the board, reduces complexity, and makes OpenLLMetry more intuitive and maintainable.

**Comment by detunjiSamuel** [comment]
Hello 👋

I just read this issue and I'd love to work on it. 

From what I understand, I'll be making changes to `sdk.traceloop.decorators` - updating `entity_method`, `aentity_method` , `aentity_class` and `entity_class` with unified versions that can handle both sync and async functions. 

Then merging the decorators like `@task`, `@workflow`, `@tool` to use these. 
I'll be using `inspect` to detect if a function is async as shown in [this StackOverflow post](https://stackoverflow.com/questions/36076619/test-if-function-or-method-is-normal-or-asynchronous).

One quick question - I'm not too familiar with what "migration guidance" means - is this about adding deprecation warnings to the async decorators like `atool` and `atask` ? 

I would love some clarification on that part!

**Comment by nirga** [comment]
Thanks @detunjiSamuel! And yes, it's keeping the old ones but warnings users that these are no longer needed + updating our docs
