### ISSUE TITLE
🚀 Feature: Milvus Instrumentation

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry#244]
### Which component is this feature for?

All Packages

### 🔖 Feature description

Instrument calls to [Milvus](https://milvus.io/docs/search.md), including adding attributes, similarly to our [Chroma](https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-chroma) instrumentation. The instrumentation should support all types of calls - streaming, non streaming, async, etc.

### 🎤 Why is this feature needed ?

Completness of OpenLLMetry

### ✌️ How do you aim to achieve this?

Similarily to other instrumentations we have in this repo.

### 🔄️ Additional Information

* Make sure to initialize this in [Traceloop SDK](https://github.com/traceloop/openllmetry/blob/main/packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py#L241).
* Add proper [tests](https://github.com/traceloop/openllmetry/tree/main/packages/traceloop-sdk/tests).

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by Josecespedesant** [comment]
Hello! Can I work on this issue?

**Comment by nirga** [comment]
Yes @Josecespedesant! Go ahead. Ping me on [slack](https://traceloop.com/slack) if you need assistance!

**Comment by Josecespedesant** [comment]
Excellent, working on it!
