### ISSUE TITLE
🐛 Bug Report: cannot override auto-instrumented packages

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry#258]
### Which component is this bug for?

Traceloop SDK

### 📜 Description

We need a way to override and specify the packages to auto-instrument. Right now we [do this automatically](https://github.com/traceloop/openllmetry/blob/main/packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py#L251C14-L251C14) based on installed packages, which might not fit everyone.

### 👟 Reproduction steps

Issues with transformer package we saw with litellm maintainer - https://github.com/BerriAI/litellm/issues/1160

### 👍 Expected behavior

-

### 👎 Actual Behavior with Screenshots

-

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by Mizba-Anjum** [comment]
Hi I tried looking at this and I made a PR #363 that adds an option to specify the packages used in an array argument in the init() function.
ex: `Traceloop.init(instruments=['openai'])`
 Let me know if it helps or could be improved!
