### ISSUE TITLE
🐛 Bug Report: hard to decipher error message when providing wrong API key

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry#290]
### Which component is this bug for?

Traceloop SDK

### 📜 Description

When providing the wrong `TRACELOOP_API_KEY` the following error is thrown, making it hard to trace back the reason (which is a bad API key). We should output a better log for that.
```
Traceback (most recent call last):
  File "/Users/nirga/vecinity/openllmetry/packages/sample-app/sample_app/prompt_registry_example_app.py", line 10, in <module>
    Traceloop.init(app_name="prompt_registry_example_app")
  File "/Users/nirga/vecinity/openllmetry/packages/traceloop-sdk/traceloop/sdk/__init__.py", line 62, in init
    Traceloop.__fetcher.run()
  File "/Users/nirga/vecinity/openllmetry/packages/traceloop-sdk/traceloop/sdk/fetcher.py", line 55, in run
    refresh_data(
  File "/Users/nirga/vecinity/openllmetry/packages/traceloop-sdk/traceloop/sdk/fetcher.py", line 144, in refresh_data
    response = fetch_url(f"{base_url}/v1/traceloop/prompts", api_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nirga/vecinity/openllmetry/packages/sample-app/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/nirga/vecinity/openllmetry/packages/sample-app/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nirga/vecinity/openllmetry/packages/sample-app/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x11492b910 state=finished raised HTTPError>]
```

### 👟 Reproduction steps

Choose a random `TRACELOOP_API_KEY` and set `TRACELOOP_BASE_URL` to `api.traceloop.com` (or leave empty).

### 👍 Expected behavior

Some output saying something like `Authorization error: invalid API key.`

### 👎 Actual Behavior with Screenshots

See log message in the description

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by cosmastech** [comment]
@nirga Looking for issues on Github that I could maybe assist with and came across this.

It looks like we're getting a 500 Internal Server Error response here. https://github.com/traceloop/openllmetry/blob/a5020db525b8595df1275d98e93ece81344646e9/packages/traceloop-sdk/traceloop/sdk/fetcher.py#L100-L101

There also does not appear to be any content. It would be dangerous to assume that any 500 response was caused by a bad API key. Is there another alternative?

**Comment by nirga** [comment]
Thanks @cosmastech! Tbh I noticed that yesterday and opened this issue to remember to look into this further.
I will fix this on the backend and update here once I'm done.

**Comment by nirga** [comment]
@cosmastech this is fixed now!

**Comment by cosmastech** [comment]
@nirga  Do you think this should raise a custom exception here? If so, do you have a particular place you'd like that defined? I'm new to Python... I was thinking it could just live in fetcher.py, but my PHP/Laravel sensibilities say it should live in a separate file 😆

**Comment by nirga** [comment]
@cosmastech haha no worries! I'm not sure I'd throw an exception here but rather just output a log message and fail silently (potentially turning off further retries, as they obviously will fail).

**Comment by ashishlakraa** [comment]
@nirga I would like to work on this issue. But I am new to this tool, can you help me any documentation or links for setting up **traceloop-sdk** in local environment for development and testing?

**Comment by nirga** [comment]
@ashishlakraa sure, you can find it in our docs - https://www.traceloop.com/docs/openllmetry/contributing/developing
