### ISSUE TITLE
🐛 Bug Report: Async and streaming Anthropic is not supported

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry#302]
### Which component is this bug for?

Anthropic Instrumentation

### 📜 Description

Anthropic provides an async API as well as a sync API: 
https://github.com/anthropics/anthropic-sdk-python?tab=readme-ov-file#async-usage

Both should be supported as part of the instrumentation

### 👟 Reproduction steps

-

### 👍 Expected behavior

-

### 👎 Actual Behavior with Screenshots

-

### 📃 Provide any additional context for the Bug.

This can be supported similarily to our OpenAI instrumentation

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by AromaticHydrocarbon** [comment]
Hello. Can I work on this issue?

**Comment by nirga** [comment]
Sure @AromaticHydrocarbon!
