### ISSUE TITLE
🚀 Feature: Add IBM Watsonx Instrumentation

### ISSUE THREAD

**Issue by gyliu513** [traceloop/openllmetry#339]
### Which component is this feature for?

Traceloop SDK

### 🔖 Feature description

Enable traceloop can collect metrics and tracing for IBM Watsonx, we have a  prototype at https://github.com/gyliu513/langX101/tree/main/otel/opentelemetry-instrumentation-watsonx

### 🎤 Why is this feature needed ?

Before OTEL community reach to an agreement of the AI Semantic Convention at https://github.com/open-telemetry/semantic-conventions/pull/639 , this repo is the best place to host most of the instrumentation for different llm providers.

### ✌️ How do you aim to achieve this?

I will create a PR based on https://github.com/gyliu513/langX101/tree/main/otel/opentelemetry-instrumentation-watsonx

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by gyliu513** [comment]
@nirga can you comment? Thanks

**Comment by nirga** [comment]
Sounds good! Thanks so much for this @gyliu513 :)
