### ISSUE TITLE
🚀 Feature: Enable IBM Instana as a Supported (and tested) destinations

### ISSUE THREAD

**Issue by gyliu513** [traceloop/openllmetry#342]
### Which component is this feature for?

Anthropic Instrumentation

### 🔖 Feature description

The supported destination do not have IBM Instana yet, we will enable Instana as well.

### 🎤 Why is this feature needed ?

Instana already support OTEL, and the instrumentation for AI can help Instana support AI Observability.

### ✌️ How do you aim to achieve this?

Test with IBM Watsonx and langchain first, depend on https://github.com/traceloop/openllmetry/pull/341

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by gyliu513** [comment]
@nirga ^^

**Comment by nirga** [comment]
Great! If this is a destination, then the change can only be in the docs repo documenting how to set this up.

**Comment by gyliu513** [comment]
Thanks @nirga , yes, that is also our expectation, some configuration and docs update should be good enough.
