### ISSUE TITLE
🚀 Feature: Support qdrant vector database

### ISSUE THREAD

**Issue by tekumara** [traceloop/openllmetry#345]
### Which component is this feature for?

Traceloop SDK

### 🔖 Feature description

Support tracing of calls to the [qdrant](https://github.com/qdrant/qdrant) vector database

### 🎤 Why is this feature needed ?

For users of qdrant

### ✌️ How do you aim to achieve this?

A new qdrant extension

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
Thanks @tekumara! Are you a maintainer there? Would love for assistance in understanding the APIs

**Comment by tekumara** [comment]
I'm somewhat familiar with the qdrant API as a user, rather than a maintainer.

**Comment by nirga** [comment]
@tekumara the instrumentation should be super simple, it's basically copy pasting [this instrumentation](https://github.com/traceloop/openllmetry/blob/main/packages/opentelemetry-instrumentation-chromadb/opentelemetry/instrumentation/chromadb/__init__.py) and specifying the right APIs you want to instrument. Would you want to try taking a stab at it?
