### ISSUE TITLE
🐛 Bug Report: error logged when using Chroma

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry#391]
### Which component is this bug for?

Chromadb Instrumentation

### 📜 Description

An error is logged when running a query with Chroma.

### 👟 Reproduction steps

Use `chromadb = "^0.4.22"`, and run the `llama_index_chroma_app.py` from the sample_app.

### 👍 Expected behavior

No error should be thrown.

### 👎 Actual Behavior with Screenshots

<img width="999" alt="Screenshot 2024-02-02 at 17 58 09" src="https://github.com/traceloop/openllmetry/assets/4224692/f41bec3c-2aef-4a01-9f63-f8995c423b30">

### 🤖 Python Version

3.9.5

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
@paolorechia I think this is a regression of #344. I removed the wrapped method you added:
```
    {
        "package": chromadb.api.segment,
        "object": "SegmentAPI",
        "method": "_query",
        "span_name": "chroma.query.segment._query"
    },
```
And the error disappeared.

**Comment by paolorechia** [comment]
@nirga sorry, I did not notice it (I guess because I was testing with console traces).

 I’ve seen a similar error while developing, and I thought I had handled all of them. I think we’re just missing a cast somewhere to the supported types.

I’m not with my desktop at the moment, but I guess one of these would be the culprit (given  the wrapped method you found already):

```
def _set_segment_query_attributes(span, kwargs):
    _set_span_attribute(span, "db.chroma.query.segment._query.collection_id", str(kwargs.get("collection_id")))


def _add_segment_query_embeddings_events(span, kwargs):
    for i, embeddings in enumerate(kwargs.get("query_embeddings", [])):
        span.add_event(
            name=f"{Events.VECTOR_DB_QUERY_EMBEDDINGS.value}.{i}",
            attributes={f"{Events.VECTOR_DB_QUERY_EMBEDDINGS.value}.{i}.vector": embeddings}
        )

```

Probably need to cast embedding here:

            attributes={f"{Events.VECTOR_DB_QUERY_EMBEDDINGS.value}.{i}.vector": embeddings}

**Comment by paolorechia** [comment]
Probably introduced in this commit, when I got ready of the cast to remove the eval in the test code

https://github.com/traceloop/openllmetry/pull/344/commits/9416fbe8272a6122138bd0a4b3ca0561048b12b4

**Comment by paolorechia** [comment]
But maybe there’s a better way to cast it to list of floats here.

**Comment by nirga** [comment]
No worries :) 
Yeah, I think it's the embeddings. I'd use `json.dumps()`

**Comment by paolorechia** [comment]
Yeah, I think that also works! Later on, I can roll a fix, if you want

**Comment by nirga** [comment]
That would be great :)

**Comment by paolorechia** [comment]
To my surprise, this isn't reproducible when using the chroma sample app I've used for developing it:

![image](https://github.com/traceloop/openllmetry/assets/5386983/30200a40-4ec5-41c2-b715-08aa7ca28a39)


Wondering what's the difference between this and the llama-index app... I guess I'll check that next

**Comment by paolorechia** [comment]
I can reproduce it when executing llama-index sample app, but couldn't figure out the exact difference. `llama-index` probably generates embeddings in a different type.

Either way, the `json` serialization fix seems to work, I'll raise a PR briefly.
![image](https://github.com/traceloop/openllmetry/assets/5386983/aaf82da1-294a-49c0-af19-ca0064365c6d)

**Comment by paolorechia** [comment]
https://github.com/traceloop/openllmetry/pull/393
