### ISSUE TITLE
🚀 Feature: IBM watsonx instrumentation ibm_watsonx_ai package support

### ISSUE THREAD

**Issue by huang-cn** [traceloop/openllmetry#441]
### Which component is this feature for?

Traceloop SDK

### 🔖 Feature description

adding `ibm_watsonx_ai` package support to IBM watsonx  traceloop instrumentation

### 🎤 Why is this feature needed ?

IBM watsonx has `ibm_watsonx_ai`  and `ibm_watson_machine_learning`  packages, the current instrumentation only support instrumentation of `ibm_watson_machine_learning`. plus the `ibm_watsonx_ai` package is also what langchain_community llms supports, so this support is also needed to get langchain watsonx trace.

### ✌️ How do you aim to achieve this?

I will create a PR based on https://github.com/huang-cn/traceloop-openllmetry/tree/watson_ml_moduel_support/packages/opentelemetry-instrumentation-watsonx

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by huang-cn** [comment]
@nirga could you comment on this? Thanks!

**Comment by huang-cn** [comment]
@nirga Yes I'm working with @gyliu513 on this. here is the `WatsonxLLM` in langchain_community: https://github.com/langchain-ai/langchain/blob/1d2aa19aeeca94f21b01c1f3ada6eb5e2defca23/libs/community/langchain_community/llms/watsonxllm.py#L169-L210, so this support is needed in order to get Watsonx trace data in langchain.

**Comment by gyliu513** [comment]
Thanks @huang-cn , look forward to the PR.

Hi @nirga , yes , this is requested as we need to support both packges, hope it is ok.
