### ISSUE TITLE
🐛 Bug Report: UI: Update time format to MM/DD/YY

### ISSUE THREAD

**Issue by gyliu513** [traceloop/openllmetry#471]
### Which component is this bug for?

Anthropic Instrumentation

### 📜 Description

Can we update the data format to MM/DD/YY, current format is DD/MM/YY

### 👟 Reproduction steps

Check filter on the UI page

### 👍 Expected behavior

Can we update the data format to MM/DD/YY, current format is DD/MM/YY

### 👎 Actual Behavior with Screenshots

<img width="746" alt="Screenshot 2024-02-22 at 9 38 34 AM" src="https://github.com/traceloop/openllmetry/assets/4461983/bcd96d7a-7847-4eb7-8bf3-c43dba3edc2d">

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
Thanks @gyliu513! While not a bug in the sdk I'll fix it in our UI to match the local system settings.
