### ISSUE TITLE
🚀 Feature: Add more properties to Span Attributes for OpenAI instrumentation

### ISSUE THREAD

**Issue by tonybaloney** [traceloop/openllmetry#479]
### Which component is this feature for?

OpenAI Instrumentation

### 🔖 Feature description

The OpenAI instrumentation is great, but is missing some span attributes compared with the httpx instrumentor that would be useful to capture.  I'd like to know what the client attributes were for the OpenAI client like the host and the deployment name. Those are in `SpanAttributes.HTTP_METHOD` and `SpanAttributes.HTTP_URL`.

### 🎤 Why is this feature needed ?

I'm using different OpenAI backends (Azure OpenAI) and want to capture the deployment name, the host name and other information that is in the client.

### ✌️ How do you aim to achieve this?

Add some additional span attributes to the trace that capture the properties of the open ai client object.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by nirga** [comment]
Thanks @tonybaloney for flagging this. It totally makes sense and we should add these attributes.

**Comment by tonybaloney** [comment]
Actually, looking at the source code, you've mostly got the implementation but it would only work with the old OpenAI SDK  (pre v1)

[_set_api_attributes](https://github.com/traceloop/openllmetry/blob/main/packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/__init__.py#L40-L44) These attributes aren't used in the new SDK. I'm happy to raise a PR to fix this. Have all the pieces running already to test it

**Comment by nirga** [comment]
Sounds good @tonybaloney 
Yeah I had some vague memory we implemented it once but might be for the old OpenAI APIs indeed.

**Comment by tonybaloney** [comment]
See #522
