### ISSUE TITLE
🐛 Bug Report: Validate if watsonx can run with python 3.8

### ISSUE THREAD

**Issue by gyliu513** [traceloop/openllmetry#529]
### Which component is this bug for?

Watsonx Instrumentation

### 📜 Description

This is a follow up for https://github.com/traceloop/openllmetry/pull/526, need check if watsonx support python 3.8

### 👟 Reproduction steps

Check https://github.com/traceloop/openllmetry/pull/526 for detail

### 👍 Expected behavior

Watsonx need to work with python 3.8

### 👎 Actual Behavior with Screenshots

Check https://github.com/traceloop/openllmetry/pull/526

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by huang-cn** [comment]
@gyliu513 the `ibm-watsonx-ai` package requires ["Python >=3.10"](https://pypi.org/project/ibm-watsonx-ai/0.1.8/) since version `0.1.1`, I think that's the only reason preventing us from using Python 3.8.

**Comment by gyliu513** [comment]
@nirga with above statement, I think Watsonx cannot support python 3.8. So for now, I think we have to disable the test until the SDK want to bump up python to 3.10, does that make sense? Thanks

**Comment by nirga** [comment]
@gyliu513 @huang-cn can we maybe use v0.1.0 in the tests then?

**Comment by huang-cn** [comment]
@nirga @gyliu513 there's only a v0.0.5 which is the earliest version can support Python 3.9, unfortunately that version doesn't has the `ModelInference` yet, we can not use it.

**Comment by nirga** [comment]
@huang-cn since we run tests on multiple python versions, maybe we can run then on Python 3.9+ only?

**Comment by huang-cn** [comment]
@nirga unfortunately the v0.0.5 is a very old version we are not able to use, for all the other versions of `ibm-watsonx-ai` they all require [Python >= 3.10](https://pypi.org/project/ibm-watsonx-ai/#history).  
is it possible we only run tests on Python 3.10+?
