### ISSUE TITLE
🚀 Feature: Declare Optional Dependencies for Traceloop SDK

### ISSUE THREAD

**Issue by paolorechia** [traceloop/openllmetry#537]
### Which component is this feature for?
Traceloop SDK

### 🔖 Feature description
We're starting to hit some issues with dependency conflicts, which prevents us from upgrading key packages that we instrument in the library.

One of these conflicts, for instance, is how weaviate-client v4 depends on pydantic>=2 but haystack v1 depends on pydantic==1.

In theory, there's no need to always have all dependencies from all instrumentations to be always resolved simultaneously. We should instead make Traceloop SDK dependency light, and declare the instrumentations as optional dependencies.

One could then, install the specific instrumentations that he desires, like this:

pip install traceloop[pinecone, openai]

### 🎤 Why is this feature needed ?
This would also enable us to simultaneously support many versions of the same libraries, as we can effectively just declare a new optional dependency for each version we're instrumenting.

✌️ How do you aim to achieve this?

Update to pyproject.toml on traceloop-sdk, needs additional research on details.

🔄️ Additional Information

Many libraries in the wild offer this, we can find one and use their configuration as a starting point.

👀 Have you spent some time to check if this feature request has been raised before?

    I checked and didn't find similar issue

Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by nirga** [comment]
Interesting! But the thing is - the instrumentations don't depend on the actual packages - so why is it an issue? I think it only happens in the sample app, no?

**Comment by paolorechia** [comment]
@nirga I think the problem is that we have these dependencies:

`[tool.poetry.group.test.dependencies]`

For instance, in Pinecone:
```
[tool.poetry.group.test.dependencies]
openai = "^1.12.0"
pytest = "8.0.2"
pytest-sugar = "1.0.0"
vcrpy = "^6.0.1"
pytest-recording = "^0.13.1"
opentelemetry-sdk = "^1.23.0"
opentelemetry-instrumentation-openai = {path="../opentelemetry-instrumentation-openai", develop=true}
pinecone-client = "^2.2.4"
```

I might be mistaken, but I think if you install traceloop-sdk locally with poetry install, it will fetch these and trigger some dependency conflicts between different instrumentations. Maybe another simpler solution could be implemented here.

**Comment by nirga** [comment]
Hmm it shouldn't since these are test dependencies, so only if installing the instrumentation directly to run should be installed.

**Comment by paolorechia** [comment]
I see, perhaps this was already fixed when the tests were pushed to separate projects? Previously they were all in traceloop-sdk, I think that’s when I had the issue.

I guess we can close this issue then.
