### ISSUE TITLE
🐛 Bug Report: Watsonx traceloop flow has many http request spans which is distracting

### ISSUE THREAD

**Issue by huang-cn** [traceloop/openllmetry#542]
### Which component is this bug for?

Watsonx Instrumentation

### 📜 Description

when using traceloop flow with watsonx, the trace data include many http request spans, which is distracting.  

### 👟 Reproduction steps

following the [traceloop openllmetry example](https://www.traceloop.com/openllmetry/integrations/observability-for-openai-with-traceloop) to instrument watsonx LLM, and output otel data to jaeger.

### 👍 Expected behavior

plan for improvement:

1. adding these domain names to traceloop-sdk tracing `EXCLUDED_URLS` to avoid generating http request spans
2. create a watson model init span to show the model initialization response time.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/traceloop/openllmetry/assets/58250676/84886351-b29f-4cf0-be75-f7ec5346132f)

### 🤖 Python Version

3.11

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by paolorechia** [comment]
My first impression is that this is not a bug but intended behavior. That being said, making it more configurable is always a good idea

**Comment by huang-cn** [comment]
@paolorechia It appears there's no simple switch to turn these http request spans off,  in the sdk tracing `EXCLUDED_URLS` we can see URLs of many api have been excluded already, we're planning to add the Watsonx api to the `EXCLUDED_URLS` to address this.

**Comment by paolorechia** [comment]
I see, I found it (https://github.com/traceloop/openllmetry/blob/3eba03e21b99cfd9b09bc46cdd1d009634f43072/packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py#L35)

Makes sense to me, I agree you can consider it a bug then 🙂

**Comment by paolorechia** [comment]
@nirga While researching for semantic conventions I’ve seen some OpenTelemetry  instrumentations define trace level.

Maybe it’s a feature to consider for traceloop, so users can adjust these kind of things?

**Comment by nirga** [comment]
@huang-cn yep, sounds good!
@paolorechia that's a good question, which span kind to use. We're starting a semantic convention working group to discuss that - https://github.com/open-telemetry/community/blob/main/projects/llm-semconv.md
