### ISSUE TITLE
🐛 Bug Report: Number of tokens not reported when streaming OpenAI/AOAI

### ISSUE THREAD

**Issue by maciejwie** [traceloop/openllmetry#627]
### Which component is this bug for?

OpenAI Instrumentation

### 📜 Description

`llm.usage.prompt_tokens` and `llm.usage.total_tokens` are not reported when streaming is used. Per discussion in Slack, this may be because this information is not included in the response from OpenAI/Azure OpenAI. Especially when `TRACELOOP_TRACE_CONTENT` is `false`, this is an important statistic and would be required for derived fields like token throughput.

### 👟 Reproduction steps

The following code correctly reports the number of tokens:
```
prompt = "Say Hi!"

response_non_streaming = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": prompt}]
)
```

The following code does not report the number of tokens:
```
prompt = "Say Hi!"

response_streaming = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": prompt}],
    stream=True
)
```

### 👍 Expected behavior

`llm.usage.prompt_tokens` and `llm.usage.total_tokens` should be reported regardless of `stream` setting.

### 👎 Actual Behavior with Screenshots

Example with non-streamed ada:
<img width="198" alt="image" src="https://github.com/traceloop/openllmetry/assets/4912878/318fd540-88cd-4149-b980-328c52bb2921">

Example with streaming gpt-3.5:
![image](https://github.com/traceloop/openllmetry/assets/4912878/51e44320-40b8-49e4-aeb0-24afb87c3e51)

### 📃 Provide any additional context for the Bug.

If this value is not reported by OpenAI/Azure OpenAI directly, then it may be a design decision of whether it's worth counting in this library, or whether only values returned by the APIs should be reported.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by Humbertzhang** [comment]
Maybe we cound use openai's [tiktoken](https://github.com/openai/tiktoken) to obtain an approximate estimation of token usage for a given text.

tiktoken will need to download an encoding file the first time it runs, and it should increase computational overhead. I think this feature should be off by default.

@nirga  What do you think about it? If you think this approach is feasible and acceptable, I'm willing in adding this feature to OpenAI's instrumentor.

**Comment by nirga** [comment]
@Humbertzhang yep I think this is the way to go, and you are right - this should be off by default.

**Comment by feng-95** [comment]
Hi @nirga @Humbertzhang, I have seen the pr https://github.com/traceloop/openllmetry/pull/661, but it seems it won't record token usage metrics  if the `enrich_token_usage` is `false` (which will be `false` for auto-instrumentation) even the response has return the usage info.  
```
def should_record_stream_token_usage():
    return Config.enrich_token_usage

```
Since tiktoken doesn't work for all model (such as our own model), would it be better to use the usage information in the response to record usage metrics if the response include usage information?
