### ISSUE TITLE
🐛 Bug Report: Sentry.io integration breaks

### ISSUE THREAD

**Issue by evisong** [traceloop/openllmetry#686]
### Which component is this bug for?

Traceloop SDK

### 📜 Description

According to https://www.traceloop.com/docs/openllmetry/integrations/sentry, Traceloop SDK should work with Sentry SDK by using OpenTelemetry as its instrumenter. However the traces are never sent out.

### 👟 Reproduction steps

1. `pip install --upgrade 'sentry-sdk[opentelemetry]'`
2. Add `sentry_sdk.init(dsn=<Your DSN>, enable_tracing=True, instrumenter="hotel",debug=True)`
3. Add `Traceloop.init(processor=SentrySpanProcessor(), propagator=SentryPropagator())`
4. Run my langchain app.

### 👍 Expected behavior

As langchain invokes LLM and other chains, traces should be sent to Sentry.io, and the console should print:

```sh
 [sentry] DEBUG: Setting up integrations (with default = True)
...
Traceloop exporting traces to a custom exporter
...
 [sentry] DEBUG: [Tracing] Create new propagation context: {'trace_id': '123456789abcdef', 'span_id': '12341234', 'parent_span_id': None, 'dynamic_sampling_context': None}
 [sentry] DEBUG: Sending envelope [envelope with 1 items (transaction)] project:123412341234 host:<DSN>.ingest.us.sentry.io
 [sentry] DEBUG: 1 event(s) pending on flush
Sentry is attempting to send 1 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
 [sentry] DEBUG: background worker flushed
...
```

### 👎 Actual Behavior with Screenshots

However, the traces are never sent out. I only see the following in console:

```sh
 [sentry] DEBUG: Setting up integrations (with default = True)
...
Traceloop exporting traces to a custom exporter
...
 [sentry] DEBUG: [Tracing] Create new propagation context: {'trace_id': '123456789abcdef', 'span_id': '12341234', 'parent_span_id': None, 'dynamic_sampling_context': None}
...
 [sentry] DEBUG: background worker got flush request
 [sentry] DEBUG: background worker flushed
...
```

### 🤖 Python Version

3.11.8

### 📃 Provide any additional context for the Bug.

I troubleshoot this issue by replacing`Traceloop.init` with `LangchainInstrumentor().instrument()`:

```python
import sentry_sdk
from opentelemetry import trace
from opentelemetry.propagate import set_global_textmap
from opentelemetry.sdk.trace import TracerProvider
from sentry_sdk.integrations.opentelemetry import SentrySpanProcessor, SentryPropagator

def setup_sentry():
    sentry_sdk.init(
        dsn=<DSN>,
        enable_tracing=True,
        instrumenter="otel",
        debug=True,
    )

    provider = TracerProvider()
    provider.add_span_processor(SentrySpanProcessor())
    trace.set_tracer_provider(provider)
    set_global_textmap(SentryPropagator())

    LangchainInstrumentor().instrument()

def my_langchain_app():
    setup_sentry()
    # ...
``` 

Both `LangchainInstrumentor` and `sentry_sdk` work as expected: langchain workflow traces are sent and can be observed on Sentry.io.

After switching back to `Traceloop.init(processor=SentrySpanProcessor(), propagator=SentryPropagator())`, it doesn't work anymore.

I've looked into the source code of both Traceloop SDK and Sentry python SDK, I find Sentry's custom `SentrySpanProcessor` relies heavily on the `on_start` method:

https://github.com/getsentry/sentry-python/blob/05d1e5ca94cc4fffcd01c46ceda6713459308404/sentry_sdk/integrations/opentelemetry/span_processor.py#L117-L178

But `TracerWrapper` replaces spans_processor's `on_start` with its own implementation `_span_processor_on_start`:

https://github.com/traceloop/openllmetry/blob/630c7b3d90cd8db8610a3c58c5979a03ce54d348/packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py#L111

This breaks Sentry's logic. 

I'm willing to provide a fix but I'm not sure how the 2 `on_start` should coexist. Could you give some suggestions? Thanks.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
Hey @evisong thanks for offering to fix this! 🙏 
What I would try to do is check if `on_start` is set, and if so store the original `on_start` in a variable, pass it to `_span_processor_on_start` and then within `_span_processor_on_start` call the original one after / before our own custom actions.
WDYT?
