### ISSUE TITLE
🐛 Bug Report:  Init failed when installing opentelemetry-instrumentation-openai

### ISSUE THREAD

**Issue by datlife** [traceloop/openllmetry#687]
### Which component is this bug for?

OpenAI Instrumentation

### 📜 Description

I'd like to install a standalone [opentelemetry-instrumentation-openai](https://github.com/traceloop/openllmetry/tree/main/packages/opentelemetry-instrumentation-openai) module. Followed the README file. After installing the module, It'd throw an exception

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dnguyen/mambaforge/envs/zgap-chatbot/lib/python3.9/site-packages/opentelemetry/instrumentation/openai/__init__.py", line 3, in <module>
    from opentelemetry.instrumentation.instrumentor import BaseInstrumentor
  File "/Users/dnguyen/mambaforge/envs/zgap-chatbot/lib/python3.9/site-packages/opentelemetry/instrumentation/instrumentor.py", line 24, in <module>
    from opentelemetry.instrumentation._semconv import (
  File "/Users/dnguyen/mambaforge/envs/zgap-chatbot/lib/python3.9/site-packages/opentelemetry/instrumentation/_semconv.py", line 19, in <module>
    from opentelemetry.semconv.trace import SpanAttributes
ModuleNotFoundError: No module named 'opentelemetry.semconv.trace'
```

### 👟 Reproduction steps

Step 1: Install opentelemetry-instrumentation-openai
```
$ poetry add opentelemetry-instrumentation-openai 
```
Step 2: Run an example code
```
from opentelemetry.instrumentation.openai import OpenAIInstrumentor
OpenAIInstrumentor().instrument()
```

### 👍 Expected behavior

No error should be reported during init step

### 👎 Actual Behavior with Screenshots

Exception error

![image](https://github.com/traceloop/openllmetry/assets/13214917/64fa85fc-45ba-4db6-a8cb-02ce85f86aac)

### 🤖 Python Version

3.9.16

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
Hey @datlife thanks for flagging this! Can you try to run `poetry add opentelemetry-semantic-conventions` and see if it resolves this? We might have some dependency missing in our `pyproject.toml`
