### ISSUE TITLE
🐛 Bug Report: Prompts and responses are only captured for OpenAI models

### ISSUE THREAD

**Issue by Simon-Stone** [traceloop/openllmetry#696]
### Which component is this bug for?

Langchain Instrumentation

### 📜 Description

When using the `ChatOpenAI` class, tracing and capturing prompts and responses works just fine. Other classes, e.g. `HuggingFaceTextGenInference` or `Llama2Chat`, emit traces, but do not capture the prompts and responses.

### 👟 Reproduction steps

Replace the `ChatOpenAI` class in the code example with `HuggingFaceTextGenInference`.

### 👍 Expected behavior

Prompts and responses should be traced for non-OpenAI models.

### 👎 Actual Behavior with Screenshots

<img width="1681" alt="image" src="https://github.com/traceloop/openllmetry/assets/18614423/143a2d22-7634-47ed-b6cb-8156a4a13099">

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by nirga** [comment]
Hey @Simon-Stone thanks! The SDK assumes you use a standard library to make the API calls (like OpenAI's, Anthropic, Cohere, etc.). Which library are you using in this case?

**Comment by Simon-Stone** [comment]
I would think so. I tried to explicitly add the `invoke` method to the wrapped methods, but it made no difference:

```python
from opentelemetry.instrumentation.langchain import (
    WRAPPED_METHODS,
    LangchainInstrumentor,
)
from opentelemetry.instrumentation.langchain.task_wrapper import task_wrapper

WRAPPED_METHODS.append(
    {
        "package": "langchain_community.llms.huggingface_text_gen_inference",
        "object": "HuggingFaceTextGenInference",
        "method": "invoke",
        "wrapper": task_wrapper,
    }
)
```

**Comment by nirga** [comment]
Interesting. I have a guess that because it's in a different package, we'll need to add that package to `_instruments`. I'll look into this in depth later.

**Comment by nirga** [comment]
@Simon-Stone managed to resolve this!

**Comment by Simon-Stone** [comment]
Outstanding! Seems to work like a charm. Thank you so much for the swift and thorough fix, @nirga !
