### ISSUE TITLE
🐛 Bug Report: Error getting model name when using langchain BedrockChat

### ISSUE THREAD

**Issue by evisong** [traceloop/openllmetry#762]
### Which component is this bug for?

Langchain Instrumentation

### 📜 Description

When using latest `opentelemetry-instrumentation-langchain@0.15.11` with the `traceloop-sdk@0.15.11` in a langchain app that works with AWS Bedrock models, `custom_chat_wrapper` throws error when getting model name in `_handle_request`.

### 👟 Reproduction steps

```python
from langchain_community.chat_models import BedrockChat

llm = BedrockChat(
    region_name="us-east-1",
    model_id="anthropic.claude-3-sonnet-20240229-v1:0",
    endpoint_url="https://bedrock-runtime.us-east-1.amazonaws.com",
    name="my_bedrock_model",
    model_kwargs={
        "max_tokens": 1024,
        "temperature": 0.5,
    },
)

chain = prompt | llm
chain.invoke("Tell a joke")
```

### 👍 Expected behavior

The Bedrock chat model should be instrumented without any errors.

### 👎 Actual Behavior with Screenshots

It throws an error:

```
 /Users/xxx/Library/Caches/pypoetry/virtualenvs/xxx/lib/python3.11/site-packages/opentelemetry/instrumentation/langchain/custom_chat_wrapper.py:43 in
 _handle_request

   40
   41 def _handle_request(span, args, kwargs, instance):
   42 │   print(instance)
 ❱ 43 │   model = instance.model if hasattr(instance, "model") else instance.model_name
   44 │   span.set_attribute(SpanAttributes.LLM_REQUEST_TYPE, LLMRequestTypeValues.CHAT.value)
   45 │   span.set_attribute(SpanAttributes.LLM_REQUEST_MODEL, model)
   46 │   span.set_attribute(SpanAttributes.LLM_RESPONSE_MODEL, model)

AttributeError: 'BedrockChat' object has no attribute 'model_name'
```

### 🤖 Python Version

3.11.8

### 📃 Provide any additional context for the Bug.

I've printed the `instance` object:

```
client=<botocore.client.BedrockRuntime object at 0x11db649d0> region_name='us-east-1'
model_id='anthropic.claude-3-haiku-20240307-v1:0' model_kwargs={'max_tokens': 1024, 'temperature': 0.5}
endpoint_url='https://bedrock-runtime.us-east-1.amazonaws.com' name='my_bedrock_model'
```

So far as I know:

* `ChatAnthropic` uses `model` or `model_name` (https://github.com/langchain-ai/langchain/blob/039b7a472d3628f2b484bf2814f9e7e677adf738/libs/partners/anthropic/langchain_anthropic/chat_models.py#L231)
* `ChatOpenAI` uses `model_name` or `model` (https://github.com/langchain-ai/langchain/blob/039b7a472d3628f2b484bf2814f9e7e677adf738/libs/partners/openai/langchain_openai/chat_models/base.py#L277)
* `BedrockChat` (`BedrockBase`) uses `model_id` (https://github.com/langchain-ai/langchain/blob/039b7a472d3628f2b484bf2814f9e7e677adf738/libs/community/langchain_community/llms/bedrock.py#L322)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by nirga** [comment]
Thanks @evisong! Would love for you to fix that as you proposed :) While you're at it - I'd wrap this in a `try-except` so that at least we won't throw an exception

**Comment by evisong** [comment]
> While you're at it - I'd wrap this in a `try-except` so that at least we won't throw an exception

@nirga I forgot to ask, do you need me to add the `try-except` in #763, or you will add it from your side?

**Comment by nirga** [comment]
If you can do it there it will be great @evisong :)
