### ISSUE TITLE
🐛 Bug Report: LLamaCPP is not found by the CustomLLMInstrumentor llamaindex class

### ISSUE THREAD

**Issue by iblancasa** [traceloop/openllmetry#774]
### Which component is this bug for?

Llamaindex Instrumentation

### 📜 Description

These lines:
https://github.com/traceloop/openllmetry/blob/8fb1504932d328ec83b07c76c81a14b75ab2c1b7/packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/custom_llm_instrumentor.py#L32-L37

Detects the custom LLMs under `llama_index.llms`. The `LLamaCPP` class is not found. If I print the `custom_llms_classes`, I  got an empty list.

If I import manually the class and append it to `custom_llms_classes`, the instrumentation works properly. Otherwise, no instrumentation is done.

### 👟 Reproduction steps

This application is not instrumented by the OpenLLmetry package but Flask is properly autoinstrumented:
```python
from llama_index.core import SimpleDirectoryReader, VectorStoreIndex
from llama_index.llms.llama_cpp import LlamaCPP
from llama_index.llms.llama_cpp.llama_utils import (
    messages_to_prompt,
    completion_to_prompt,
)
import flask
from time import sleep
import requests

app = flask.Flask(__name__)

llm = LlamaCPP(
    # "https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF/resolve/main/llama-2-7b-chat.Q4_K_M.gguf"
    model_path="llama-2-7b-chat.Q4_K_M.gguf",
    temperature=0.1,
    max_new_tokens=256,
    # llama2 has a context window of 4096 tokens, but we set it lower to allow for some wiggle room
    context_window=3900,
    # set to at least 1 to use GPU
    model_kwargs={"n_gpu_layers": 1},
    # transform inputs into Llama2 format
    messages_to_prompt=messages_to_prompt,
    completion_to_prompt=completion_to_prompt,
    verbose=False,
)

@app.route('/', methods = ['POST', 'GET'])
def root():
    sleep(0.35)
    prompt = "hello how are you doing?"

    if flask.request.method == 'POST':
        question = flask.request.json["question"]
        if question:
            prompt = question

    text = llm.complete(prompt)
    sleep(2)
    return flask.Response(text.text)

if __name__ == "__main__":
    app.run()
```

```sh
opentelemetry-instrument --exporter_otlp_insecure=true \ 
    --traces_exporter otlp \
    --metrics_exporter otlp \
    --service_name llmdemo \
    --exporter_otlp_traces_endpoint http://0.0.0.0:4317 --exporter_otlp_metrics_endpoint 0.0.0.0:4317 \
    python app.py

```

### 🤖 Python Version

3.12.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
Thanks @iblancasa! 
Which LlamaIndex version are you using?

**Comment by iblancasa** [comment]
I'm using version `0.10.26`.
