### ISSUE TITLE
🐛 Bug Report: AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by TaylorN15** [traceloop/openllmetry#853]
### Which component is this bug for?

OpenAI Instrumentation

### 📜 Description

I am using Azure OpenAI behind an Application Gateway with content filtering enabled on the service. With streamed responses, they often fail with an exception `"AttributeError: 'NoneType' object has no attribute 'get'"`.

I am yet to determine if the response being returned is malformed, as I expect `delta` to always be returned, even if an empty dictionary. However, perhaps the telemetry library should handle this safely.

### 👟 Reproduction steps

Unfortunately, I cannot provide repro steps. I suspect this may have something to do with the [asynchronous content filtering](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/content-filter?tabs=warning%2Cpython-new#asynchronous-modified-filter) in Azure.

### 👍 Expected behavior

Not throw exceptions

### 👎 Actual Behavior with Screenshots

```
  File "/tmp/8dc6026861d719f/antenv/lib/python3.10/site-packages/opentelemetry/instrumentation/openai/shared/chat_wrappers.py", line 486, in _abuild_from_streaming_response
    _accumulate_stream_items(item, complete_response)
  File "/tmp/8dc6026861d719f/antenv/lib/python3.10/site-packages/opentelemetry/instrumentation/openai/shared/chat_wrappers.py", line 543, in _accumulate_stream_items
    if delta.get("content"):
```

### 🤖 Python Version

3.10

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
Thanks @TaylorN15 I'll look into that.
Can you tell me which OpenAI version you're using?
(BTW, this should never throw an exception, I'm just about to fix that anyway in #748)

**Comment by TaylorN15** [comment]
Are you referring to the OpenAI SDK version? 1.17.1

**Comment by TaylorN15** [comment]
Thanks @nirga - when will this be released?

**Comment by nirga** [comment]
@TaylorN15 already released!
