### ISSUE TITLE
🚀 Feature: Update semantic convention based on latest GenAI Semantion Convention

### ISSUE THREAD

**Issue by gyliu513** [traceloop/openllmetry#880]
### Which component is this feature for?

All Packages

### 🔖 Feature description

Update semantic convention based on latest GenAI Semantion Convention https://github.com/open-telemetry/semantic-conventions/blob/main/docs/attributes-registry/llm.md

### 🎤 Why is this feature needed ?

GenAI Semantic Convetion is a standard for all LLM providers

### ✌️ How do you aim to achieve this?

Update Gen AI Semantic Convention

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by gyliu513** [comment]
@nirga comments?

**Comment by nirga** [comment]
@gyliu513 wanna help here? 😅

**Comment by gyliu513** [comment]
Yes, I can help @nirga
