### ISSUE TITLE
🚀 Feature: Add support for new pinecone versions

### ISSUE THREAD

**Issue by tobiashanl** [traceloop/openllmetry#896]
### Which component is this feature for?

Pinecone Instrumentation

### 🔖 Feature description

The pinecone instrumentation only supports the following versions
`_instruments = ("pinecone-client ~= 2.2.2",)
`
The newest version of pinecone is [3.2.2](https://pypi.org/project/pinecone-client/), which should be supported as well.

### 🎤 Why is this feature needed ?

So we can use the pinecone instrumentation in our project, which uses pinecone versions > 3

### ✌️ How do you aim to achieve this?

Update the pinecone instrumentation to include support for newer versions > 3

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
Great timing @tobiashanl, I'm working on that as we speak
