### ISSUE TITLE
🚀 Feature: Add Azure Application Insights as an open telemetry destination

### ISSUE THREAD

**Issue by aavetis** [traceloop/openllmetry#93]
### Which component is this feature for?

OpenAI Instrumentation

### 🔖 Feature description

In addition to the [destinations currently supported](https://www.traceloop.com/docs/python-sdk/exporting) to catch traces, it would be great to extend and include Azure Application Insights. OpenTelemetry is a key recommendation for almost any solution deployed on Azure as they should be tracking traces and metrics, and it would be great to have native support.

I was going to add links to Azure documentation for OTEL + App Insights... Realized it might just be easier to send this ChatGPT instruction for a sample Python app instrumented with OTEL, sending traces to App Insights.

https://chat.openai.com/share/8b6cc9a7-b8c5-4dea-8e0b-7c6728ff40a0

### 🎤 Why is this feature needed ?

Holistic Azure solution, e.g. using Azure OpenAI and sending metrics to Azure Application Insights. All data would be airgapped and stored in your own subscription.

### ✌️ How do you aim to achieve this?

Support Azure App Insights as a trace export destination, using instrumentation key and endpoint.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by nirga** [comment]
Sounds good @aavetis! Indeed it makes sense. 
Let me know once you verified that it works and update the docs in this repo (under `/docs`) and the README. We'll then announce that support with proper credit 😄

**Comment by aavetis** [comment]
<img width="1718" alt="image" src="https://github.com/traceloop/openllmetry/assets/3076502/43a793d2-9c57-45a7-8cf0-da942abe0a41">

one thing - it seems that all telemetry goes through Traceloop (the saas) before landing in the final destination. is there a way to turn that off? while personally i think that's very cool how you can setup demo dashboards for people to get an idea of how great the platform is, it's a concern for any real production scenario. definitely want to keep your LLM logs and traces isolated.

**Comment by nirga** [comment]
Can you try passing your exporter to the sdk's init function? It just that we have an exporter we define internally in the sdk so that's what you're seeing - traces are sent to both destinations in parallel.

**Comment by aavetis** [comment]
Confirmed, when I explicitly pass in the config, it ONLY shows up in Azure and not in Traceloop dashboard. However, it appears the open dashboard is created anyway, just stays empty if the exporter is set. 

```
# this appears to ensure traces are only sent to your desired exporter
exporter = AzureMonitorTraceExporter(connection_string="InstrumentationKey=.......")
Traceloop.init(app_name="your_app_name", exporter=exporter)
```

As you can see, the dashboard is still created (just a note). 
<img width="491" alt="image" src="https://github.com/traceloop/openllmetry/assets/3076502/34192c08-6742-49ae-b581-4200fa53af70">

**Comment by nirga** [comment]
Huh! That's a bug. Fixed in #96. 
@aavetis can you add the details of how you set this up in the docs?

**Comment by aavetis** [comment]
will work on getting in the docs.

on another note, are Metrics / MeterProvider expected to work? i've noticed traces, spans, and dependencies are all tracked seamlessly.

but i haven't been able to see custom metrics (counters) getting passed down, not sure if i'm making a mistake or if sdk isn't expected to support it.
https://opentelemetry.io/docs/specs/otel/metrics/api/#meter-operations

**Comment by nirga** [comment]
Not yet, hopefully soon :)

**Comment by drewby** [comment]
> ```python
> SimpleSpanProcessor
> ```

It may be better to document use of APPLICATIONINSIGHTS_CONNECTION_STRING env variable as a good practice. I believe you can then even omit it from the exporter constructor to simplify the code. 

```python
Traceloop.init(app_name="your_app_name", exporter=AzureMonitorTraceExporter())
```

**Comment by nirga** [comment]
FYI @aavetis docs have been moved to a separate repo - https://github.com/traceloop/docs 
(To support the fact that we now have a JS SDK as well)

**Comment by nirga** [comment]
@aavetis any update on this?

**Comment by aavetis** [comment]
https://github.com/traceloop/docs/pull/2

**Comment by aavetis** [comment]
Closing as https://github.com/traceloop/docs/pull/2 is merged and deployed
